<a href="https://colab.research.google.com/github/Karmabir-Brahma/ML/blob/master/Copy_of_combine_teeth_and_market.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install bodotokenizer

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
corpus1 = [ 'मैया थांनाय सानखालि मादै मैनानि फिसाज्लाया , सक्लेट,  बायदि-बायदि गोदै मेथाय जाबोनानै हाथाइ साजादों । उनाव डाक्टरनाव थांना नायनाइआवसो  हाथाइ एम्फौ जाजादों होनना मोनथि मोनदोंमोन । दा एम्फौ जानायखौ बख जाना बोरायबायदि हाथाइ साल- ल नुबाय बाबुखौ । नै आगै नोंबो बांद्राइ गोदै जाबा बोराय साल जागोन ।  बिगै मिनिसा्ंआबो बिब सैनानि खोन्थानाय मादै मैनानि फिसाज्ला हाथाइ एमफौ  जाजानाय जाथायखौ खोनानो मोनना गिख्रंना बुङो - दे होनबा आब एबाराव आं बांद्राय गोदै मेथाइ (खाजा) जाथ ला । बिब सैनायाबो खेलायनानै बुंदेरबावो - दाजाखा नङाब्ला नोंखौ फरायसालियाव बयबो साल बोराय होनना गाबज्रिगोन । होनबाथाय नों ……. बिगै मिनिस्रां आ बिब जंखाइनायखौ लाजि मोनना बिब खौ बिखुंआव फंसे खेलाइनायजों बुयो , नै आब आंखौ बिदि होनना दाजंखाइ , बुंबायना बांद्राय गोदै जाला होनना । अखानायै मादै मैनानि फिसाज्ला सोमखोरा हाथाइ साल खौ लाना फरायसालि थाङो । फरायसालियाव माखासे गावनि लोगोफोरजों जंखाय जायो - बोराय साल होनना । सोमखोरा लाजिनाय मोननानै सासु- मासु जाना मिनिस्लु जानानैल थायो । मिनिस्रांआबो सोमखोर जोंनो ज फरायनाय , बियो बिनि सेराव थानानै गावसिनि माखासे लोगोफोरखौ बुङो  - बेनिखाइनो दिनैनिफ्राय नोंसोरबो बांद्राय गोदै- गोदै मेथाइ जानो नाङा,  नङाबा सोमखोर बायदि हाथाइ गनाय साल बोराय जाजागोन । बे समावनो मिनिस्रांनि बुंफुबाय थानायावनो बिसोरनि लोगोफोरनि गेजेराव सासे मैखोम होननाय लोगोआ - मिनिस्रांनि बाथ्राखौ एंब्राना बुङो - जेबो बिदि जाया , आंनो सानफ्रोम्बो जाबाय थायो नाथाय जेबो बिदि जायाखै होनना मिनिस्रां , सोमखोर आरो माखासे लोगोफोरनि मोखांआव फाइब स्टार(5star ) सक्लेट जाना दिन्थियो  । दिना थाङो   आरो फैयो , मैखोमाबो गोदै जानायखौ दोनथ आ सानफ्रोम्बो जायो । बिदियैनो सानाबो हाबथानै बारलाङो । साननै सानथामसो थाबावना एबा हाबथा मोननै आरो खावसे साननि उनाव हाथाइ साजायो मैखोमा । साना गाबख्रावबाय थानाइआव बिनि बिफा - बिमाया बेखौ डक्टर नाव लांना हाथाइ एमफौ जानायखौ बखना होयो । अखानायै मैखोमा फरायसासियाव थांना मिनिस्रां आरो सोमखोरनि खाथियाव थांना बुंहैयो - गावनि एंब्राना बुंनानै खोथा मानियैया गोरोनथि जाबाय । दिनै आंनाबो हाथाइ एमफौ जाजाबाय, थाइसे नङा ,थानै नङा थाइथाम हाथाइ एमफौ जाजाना बख नांबाय । नोंसिनि खोथा बुंनायखौ आं गनायना जानाङामोन । अब्ला बिदि जानाय नङामोन । निमाहा होदो लोगो होननानै मैखोमा बिसिनियाव खेमाहा बियो ।']

In [3]:
corpus2 = ['दिनै गसाइगाॅव आव शनिबार हाथाइ जायो । दिनै नि सानाव गोबां गामिनि गलादारफोरानो न नि गायनाइ मैगं-थाइगं आरि फानफैयो ।  एसेल राङैनो मैगं -थाइगंखौबो मोनबोयो । बेनिखाइनो दिनै मादै बिना आरो आनै सोमस्रिजों लोगो नांना हाथाइआव थांगोन । आबै गावदांआबो बिसोरजोंनो न नि मैगं थाइगं फानहैनो थांफागोन  ।गमामायैनो सानजौफुनि नै (2) रिंगासोआव मादै बिना  आरो आनै सोमसि् जों लोगोसे आबै गावदांआबो मैगं - थाइगं फानहैनो हाथाइआव थांफायो  । आबै गावदांमोननि न आ गसाइगाव टाउननि बेसेबांबा गोजान जायो ,गामियावबो बेबादि हाथाइ गिदिर गैया खालामगा् जायगाबो गैया । हारसिंयै फैनायावबो खस्थ जायो थेवो आबै गावदांआ मैगं - थाइगंखौ फाफ्लियाव खे- खे  रुजुनना लाबोयो गाविनि उदै आरो फिसौजोनि उदै थाइसेखौ सुफुंनो । आबैनि फिसाज्ला सासेल आरो बिहामजोआ थाम बोसोरनि सिगांनो सोरगोआव थाहैबाय ।   दा जिनै( 12) - बोसोर बैसो जानाय फिसौजो जोमैया, जेब्ला बिबैया हाथाइ आव मैगं- थाइगं फाननो थाङो अब्ला बियो ननि खामानिखौ मावना दोनजोबो । आबैआबो दिनै हाथाइआव सौहैगो् मोना गावनि जिरायगा् जायगायाव जिरायना मैगं - थाइगं फाननायखौ जागायजेनो । ओजों मादै बिना आरो आनै सोमसि्मोनाबो गसाइगाँव टाउनाव गोबावजों फैनाय ,बेनिखानो बिसोर सानैजों एसे गसाइगाँव टाउनखौ बेरायगो्ना ,  उनाव मैगं - थाइगं फानगा् हाथाइसिम फैफिनना आबैनि फानफैनाय मैगं निफा्यबो बाइयो आरो गुबुन जायगानिफा्य फानफैनाय गलादारि फोरनिफा्इबो मैगं लाना गिदिं फिननो नागिरो । नाथाइ आबैना मैगंआ एसे नांबाव नांगौ दंबावोमोन,  सानाबो बारा हाबदा्इआखै,  फारसेथिं आबैआ हारसिंयै मोनाबे्बाबो हारसिंयै फैफिननो  रोङा। बेनिखानो नांजोबाबाबो आबै गावदांआ थफ्ला बोनफिनना बिसोरजोंनो हाथाइनिफा्य फैपाफिननो होनना ओंखारो । बे समावनो सासे सेंगा्या आबैखौ  लाखिना आदा् थानाय मैगंखौ बायना लाजोबनो होनना मैगंफोरखौ थफ्लानिफा्य बरन होयो । सेंगा्या मैगं नायहोलां नो आबैनि गामि, आरो गामिनि हालोदफोरखौ फारि-फारि सोंना लायो । दानदिसे उनाव गामिनि हालोद आरो आंखाल खौ नुना/ मोनथि मोनना सेंगा्या दुखु मोनो आरो दानथामसोनि गेजेरावनो आबै गावदां मोननि गामियाव बेसेबांबा गुवार जायगा बायनानै सानफो्मबो हाथाइ जानाय बायदि गावनि रांजोंनो राहा दिहुनना होयो । जाहाथे   बयबो गलादारियानो गामिनि हाथाइआवनो बायदि रोखोमनि बेसाद मुवा फानना जिउ खुलांनो  होयो । दा आबै गावदांआबो बेयावनो गावनि निजा गला लुना मैगं- थाइगं फानसै , बेजोंनो फिसौजो जोमैखौबो आबैया लासै- लासैयैनो गोजौ थाखोसिम फोरोंलांनो हाबाय ।']

In [4]:
from bodotokenizer import tokenize
tokenized_sentenc1 = []
tokenized_sentence2 = []
results1 = []
results2 = []


for sen in corpus1:
    tokenized1 = tokenize(sen)
for sen in corpus2:
    tokenized2 = tokenize(sen)

In [5]:
tokenized1

'मैया थांनाय सानखालि मादै मैनानि फिसाज्लाया , सक्लेट , बायदि - बायदि गोदै मेथाय जाबोनानै हाथाइ साजादों । उनाव डाक्टरनाव थांना नायनाइआवसो हाथाइ एम्फौ जाजादों होनना मोनथि मोनदोंमोन । दा एम्फौ जानायखौ बख जाना बोरायबायदि हाथाइ साल - ल नुबाय बाबुखौ । नै आगै नोंबो बांद्राइ गोदै जाबा बोराय साल जागोन । बिगै मिनिसा्ंआबो बिब सैनानि खोन्थानाय मादै मैनानि फिसाज्ला हाथाइ एमफौ जाजानाय जाथायखौ खोनानो मोनना गिख्रंना बुङो - दे होनबा आब एबाराव आं बांद्राय गोदै मेथाइ ( खाजा ) जाथ ला । बिब सैनायाबो खेलायनानै बुंदेरबावो - दाजाखा नङाब्ला नोंखौ फरायसालियाव बयबो साल बोराय होनना गाबज्रिगोन । होनबाथाय नों …… . बिगै मिनिस्रां आ बिब जंखाइनायखौ लाजि मोनना बिब खौ बिखुंआव फंसे खेलाइनायजों बुयो , नै आब आंखौ बिदि होनना दाजंखाइ , बुंबायना बांद्राय गोदै जाला होनना । अखानायै मादै मैनानि फिसाज्ला सोमखोरा हाथाइ साल खौ लाना फरायसालि थाङो । फरायसालियाव माखासे गावनि लोगोफोरजों जंखाय जायो - बोराय साल होनना । सोमखोरा लाजिनाय मोननानै सासु - मासु जाना मिनिस्लु जानानैल थायो । मिनिस्रांआबो सोमखोर जोंनो ज फरायनाय , बियो बिनि सेराव थ

In [6]:
tokenized2

'दिनै गसाइगाॅव आव शनिबार हाथाइ जायो । दिनै नि सानाव गोबां गामिनि गलादारफोरानो न नि गायनाइ मैगं - थाइगं आरि फानफैयो । एसेल राङैनो मैगं - थाइगंखौबो मोनबोयो । बेनिखाइनो दिनै मादै बिना आरो आनै सोमस्रिजों लोगो नांना हाथाइआव थांगोन । आबै गावदांआबो बिसोरजोंनो न नि मैगं थाइगं फानहैनो थांफागोन । गमामायैनो सानजौफुनि नै ( 2 ) रिंगासोआव मादै बिना आरो आनै सोमसि् जों लोगोसे आबै गावदांआबो मैगं - थाइगं फानहैनो हाथाइआव थांफायो । आबै गावदांमोननि न आ गसाइगाव टाउननि बेसेबांबा गोजान जायो , गामियावबो बेबादि हाथाइ गिदिर गैया खालामगा् जायगाबो गैया । हारसिंयै फैनायावबो खस्थ जायो थेवो आबै गावदांआ मैगं - थाइगंखौ फाफ्लियाव खे - खे रुजुनना लाबोयो गाविनि उदै आरो फिसौजोनि उदै थाइसेखौ सुफुंनो । आबैनि फिसाज्ला सासेल आरो बिहामजोआ थाम बोसोरनि सिगांनो सोरगोआव थाहैबाय । दा जिनै ( 12 ) - बोसोर बैसो जानाय फिसौजो जोमैया , जेब्ला बिबैया हाथाइ आव मैगं - थाइगं फाननो थाङो अब्ला बियो ननि खामानिखौ मावना दोनजोबो । आबैआबो दिनै हाथाइआव सौहैगो् मोना गावनि जिरायगा् जायगायाव जिरायना मैगं - थाइगं फाननायखौ जागायजेनो । ओजों मादै बिना आरो आ

In [7]:
# Existing Code
# def remove_punctuation(corpus):
#     punctuations = [',' , '।', '(',')', '-', '……','.', "'", ]
#     results = []
#     for text in corpus:
#         tmp = text.split()
#         print(tmp)
#         for punctuation in punctuations:
#             if punctuation in tmp:
#                 tmp.remove(punctuation)
#         results.append(" ".join(tmp))
    
#     return results

In [8]:
# New Code

# Remove Punctuation
def remove_punctuation(corpus):
    punctuations = [',' , '।', '(',')', '-', '……','.', "'", ]
    results = []

    sentences = corpus.split()
#     print(sentences)
    for sen in sentences:
        if sen not in punctuations:
            results.append(sen)
    return results

In [9]:
corpus1 = remove_punctuation(tokenized1)

In [10]:
c1=corpus1

In [11]:
c1

['मैया',
 'थांनाय',
 'सानखालि',
 'मादै',
 'मैनानि',
 'फिसाज्लाया',
 'सक्लेट',
 'बायदि',
 'बायदि',
 'गोदै',
 'मेथाय',
 'जाबोनानै',
 'हाथाइ',
 'साजादों',
 'उनाव',
 'डाक्टरनाव',
 'थांना',
 'नायनाइआवसो',
 'हाथाइ',
 'एम्फौ',
 'जाजादों',
 'होनना',
 'मोनथि',
 'मोनदोंमोन',
 'दा',
 'एम्फौ',
 'जानायखौ',
 'बख',
 'जाना',
 'बोरायबायदि',
 'हाथाइ',
 'साल',
 'ल',
 'नुबाय',
 'बाबुखौ',
 'नै',
 'आगै',
 'नोंबो',
 'बांद्राइ',
 'गोदै',
 'जाबा',
 'बोराय',
 'साल',
 'जागोन',
 'बिगै',
 'मिनिसा्ंआबो',
 'बिब',
 'सैनानि',
 'खोन्थानाय',
 'मादै',
 'मैनानि',
 'फिसाज्ला',
 'हाथाइ',
 'एमफौ',
 'जाजानाय',
 'जाथायखौ',
 'खोनानो',
 'मोनना',
 'गिख्रंना',
 'बुङो',
 'दे',
 'होनबा',
 'आब',
 'एबाराव',
 'आं',
 'बांद्राय',
 'गोदै',
 'मेथाइ',
 'खाजा',
 'जाथ',
 'ला',
 'बिब',
 'सैनायाबो',
 'खेलायनानै',
 'बुंदेरबावो',
 'दाजाखा',
 'नङाब्ला',
 'नोंखौ',
 'फरायसालियाव',
 'बयबो',
 'साल',
 'बोराय',
 'होनना',
 'गाबज्रिगोन',
 'होनबाथाय',
 'नों',
 'बिगै',
 'मिनिस्रां',
 'आ',
 'बिब',
 'जंखाइनायखौ',
 'लाजि',
 'मोनना',
 'बिब',
 'खौ',
 'बिखुंआव',


In [12]:
corpus1

['मैया',
 'थांनाय',
 'सानखालि',
 'मादै',
 'मैनानि',
 'फिसाज्लाया',
 'सक्लेट',
 'बायदि',
 'बायदि',
 'गोदै',
 'मेथाय',
 'जाबोनानै',
 'हाथाइ',
 'साजादों',
 'उनाव',
 'डाक्टरनाव',
 'थांना',
 'नायनाइआवसो',
 'हाथाइ',
 'एम्फौ',
 'जाजादों',
 'होनना',
 'मोनथि',
 'मोनदोंमोन',
 'दा',
 'एम्फौ',
 'जानायखौ',
 'बख',
 'जाना',
 'बोरायबायदि',
 'हाथाइ',
 'साल',
 'ल',
 'नुबाय',
 'बाबुखौ',
 'नै',
 'आगै',
 'नोंबो',
 'बांद्राइ',
 'गोदै',
 'जाबा',
 'बोराय',
 'साल',
 'जागोन',
 'बिगै',
 'मिनिसा्ंआबो',
 'बिब',
 'सैनानि',
 'खोन्थानाय',
 'मादै',
 'मैनानि',
 'फिसाज्ला',
 'हाथाइ',
 'एमफौ',
 'जाजानाय',
 'जाथायखौ',
 'खोनानो',
 'मोनना',
 'गिख्रंना',
 'बुङो',
 'दे',
 'होनबा',
 'आब',
 'एबाराव',
 'आं',
 'बांद्राय',
 'गोदै',
 'मेथाइ',
 'खाजा',
 'जाथ',
 'ला',
 'बिब',
 'सैनायाबो',
 'खेलायनानै',
 'बुंदेरबावो',
 'दाजाखा',
 'नङाब्ला',
 'नोंखौ',
 'फरायसालियाव',
 'बयबो',
 'साल',
 'बोराय',
 'होनना',
 'गाबज्रिगोन',
 'होनबाथाय',
 'नों',
 'बिगै',
 'मिनिस्रां',
 'आ',
 'बिब',
 'जंखाइनायखौ',
 'लाजि',
 'मोनना',
 'बिब',
 'खौ',
 'बिखुंआव',


In [13]:
corpus2 = remove_punctuation(tokenized2)

In [14]:
c2=corpus2

In [15]:
corpus2

['दिनै',
 'गसाइगाॅव',
 'आव',
 'शनिबार',
 'हाथाइ',
 'जायो',
 'दिनै',
 'नि',
 'सानाव',
 'गोबां',
 'गामिनि',
 'गलादारफोरानो',
 'न',
 'नि',
 'गायनाइ',
 'मैगं',
 'थाइगं',
 'आरि',
 'फानफैयो',
 'एसेल',
 'राङैनो',
 'मैगं',
 'थाइगंखौबो',
 'मोनबोयो',
 'बेनिखाइनो',
 'दिनै',
 'मादै',
 'बिना',
 'आरो',
 'आनै',
 'सोमस्रिजों',
 'लोगो',
 'नांना',
 'हाथाइआव',
 'थांगोन',
 'आबै',
 'गावदांआबो',
 'बिसोरजोंनो',
 'न',
 'नि',
 'मैगं',
 'थाइगं',
 'फानहैनो',
 'थांफागोन',
 'गमामायैनो',
 'सानजौफुनि',
 'नै',
 '2',
 'रिंगासोआव',
 'मादै',
 'बिना',
 'आरो',
 'आनै',
 'सोमसि्',
 'जों',
 'लोगोसे',
 'आबै',
 'गावदांआबो',
 'मैगं',
 'थाइगं',
 'फानहैनो',
 'हाथाइआव',
 'थांफायो',
 'आबै',
 'गावदांमोननि',
 'न',
 'आ',
 'गसाइगाव',
 'टाउननि',
 'बेसेबांबा',
 'गोजान',
 'जायो',
 'गामियावबो',
 'बेबादि',
 'हाथाइ',
 'गिदिर',
 'गैया',
 'खालामगा्',
 'जायगाबो',
 'गैया',
 'हारसिंयै',
 'फैनायावबो',
 'खस्थ',
 'जायो',
 'थेवो',
 'आबै',
 'गावदांआ',
 'मैगं',
 'थाइगंखौ',
 'फाफ्लियाव',
 'खे',
 'खे',
 'रुजुनना',
 'लाबोयो',
 'गाविनि',
 'उदै',
 'आरो',
 '

In [16]:
# Existing Code
# def remove_stop_words(corpus):
#     stop_words = ['आरो', 'ए ', 'एबा', 'एबा', 'जेरैनों', 'सोर', ' बब']
#     results = []
#     for text in corpus:
#         tmp = text.split(' ')
#         for stop_word in stop_words:
#             if stop_word in tmp:
#                 tmp.remove(stop_word)
#         results.append(" ".join(tmp))
    
#     return results

In [17]:
# New Code
# Remove Stop Words
def remove_stop_words(corpus):
    stop_words = ['आरो', 'ए ', 'एबा', 'जेरैनों', 'सोर', 'बब']
    results = []
    stop = []

    for sen in corpus:
        if sen not in stop_words:
            results.append(sen)
    return results

In [18]:
corpus1 = remove_stop_words(corpus1)

In [19]:
corpus2 = remove_stop_words(corpus2)

In [20]:
corpus1

['मैया',
 'थांनाय',
 'सानखालि',
 'मादै',
 'मैनानि',
 'फिसाज्लाया',
 'सक्लेट',
 'बायदि',
 'बायदि',
 'गोदै',
 'मेथाय',
 'जाबोनानै',
 'हाथाइ',
 'साजादों',
 'उनाव',
 'डाक्टरनाव',
 'थांना',
 'नायनाइआवसो',
 'हाथाइ',
 'एम्फौ',
 'जाजादों',
 'होनना',
 'मोनथि',
 'मोनदोंमोन',
 'दा',
 'एम्फौ',
 'जानायखौ',
 'बख',
 'जाना',
 'बोरायबायदि',
 'हाथाइ',
 'साल',
 'ल',
 'नुबाय',
 'बाबुखौ',
 'नै',
 'आगै',
 'नोंबो',
 'बांद्राइ',
 'गोदै',
 'जाबा',
 'बोराय',
 'साल',
 'जागोन',
 'बिगै',
 'मिनिसा्ंआबो',
 'बिब',
 'सैनानि',
 'खोन्थानाय',
 'मादै',
 'मैनानि',
 'फिसाज्ला',
 'हाथाइ',
 'एमफौ',
 'जाजानाय',
 'जाथायखौ',
 'खोनानो',
 'मोनना',
 'गिख्रंना',
 'बुङो',
 'दे',
 'होनबा',
 'आब',
 'एबाराव',
 'आं',
 'बांद्राय',
 'गोदै',
 'मेथाइ',
 'खाजा',
 'जाथ',
 'ला',
 'बिब',
 'सैनायाबो',
 'खेलायनानै',
 'बुंदेरबावो',
 'दाजाखा',
 'नङाब्ला',
 'नोंखौ',
 'फरायसालियाव',
 'बयबो',
 'साल',
 'बोराय',
 'होनना',
 'गाबज्रिगोन',
 'होनबाथाय',
 'नों',
 'बिगै',
 'मिनिस्रां',
 'आ',
 'बिब',
 'जंखाइनायखौ',
 'लाजि',
 'मोनना',
 'बिब',
 'खौ',
 'बिखुंआव',


In [21]:
corpus2

['दिनै',
 'गसाइगाॅव',
 'आव',
 'शनिबार',
 'हाथाइ',
 'जायो',
 'दिनै',
 'नि',
 'सानाव',
 'गोबां',
 'गामिनि',
 'गलादारफोरानो',
 'न',
 'नि',
 'गायनाइ',
 'मैगं',
 'थाइगं',
 'आरि',
 'फानफैयो',
 'एसेल',
 'राङैनो',
 'मैगं',
 'थाइगंखौबो',
 'मोनबोयो',
 'बेनिखाइनो',
 'दिनै',
 'मादै',
 'बिना',
 'आनै',
 'सोमस्रिजों',
 'लोगो',
 'नांना',
 'हाथाइआव',
 'थांगोन',
 'आबै',
 'गावदांआबो',
 'बिसोरजोंनो',
 'न',
 'नि',
 'मैगं',
 'थाइगं',
 'फानहैनो',
 'थांफागोन',
 'गमामायैनो',
 'सानजौफुनि',
 'नै',
 '2',
 'रिंगासोआव',
 'मादै',
 'बिना',
 'आनै',
 'सोमसि्',
 'जों',
 'लोगोसे',
 'आबै',
 'गावदांआबो',
 'मैगं',
 'थाइगं',
 'फानहैनो',
 'हाथाइआव',
 'थांफायो',
 'आबै',
 'गावदांमोननि',
 'न',
 'आ',
 'गसाइगाव',
 'टाउननि',
 'बेसेबांबा',
 'गोजान',
 'जायो',
 'गामियावबो',
 'बेबादि',
 'हाथाइ',
 'गिदिर',
 'गैया',
 'खालामगा्',
 'जायगाबो',
 'गैया',
 'हारसिंयै',
 'फैनायावबो',
 'खस्थ',
 'जायो',
 'थेवो',
 'आबै',
 'गावदांआ',
 'मैगं',
 'थाइगंखौ',
 'फाफ्लियाव',
 'खे',
 'खे',
 'रुजुनना',
 'लाबोयो',
 'गाविनि',
 'उदै',
 'फिसौजोनि',
 'उदै',
 'थाइ

In [22]:
corpus1

['मैया',
 'थांनाय',
 'सानखालि',
 'मादै',
 'मैनानि',
 'फिसाज्लाया',
 'सक्लेट',
 'बायदि',
 'बायदि',
 'गोदै',
 'मेथाय',
 'जाबोनानै',
 'हाथाइ',
 'साजादों',
 'उनाव',
 'डाक्टरनाव',
 'थांना',
 'नायनाइआवसो',
 'हाथाइ',
 'एम्फौ',
 'जाजादों',
 'होनना',
 'मोनथि',
 'मोनदोंमोन',
 'दा',
 'एम्फौ',
 'जानायखौ',
 'बख',
 'जाना',
 'बोरायबायदि',
 'हाथाइ',
 'साल',
 'ल',
 'नुबाय',
 'बाबुखौ',
 'नै',
 'आगै',
 'नोंबो',
 'बांद्राइ',
 'गोदै',
 'जाबा',
 'बोराय',
 'साल',
 'जागोन',
 'बिगै',
 'मिनिसा्ंआबो',
 'बिब',
 'सैनानि',
 'खोन्थानाय',
 'मादै',
 'मैनानि',
 'फिसाज्ला',
 'हाथाइ',
 'एमफौ',
 'जाजानाय',
 'जाथायखौ',
 'खोनानो',
 'मोनना',
 'गिख्रंना',
 'बुङो',
 'दे',
 'होनबा',
 'आब',
 'एबाराव',
 'आं',
 'बांद्राय',
 'गोदै',
 'मेथाइ',
 'खाजा',
 'जाथ',
 'ला',
 'बिब',
 'सैनायाबो',
 'खेलायनानै',
 'बुंदेरबावो',
 'दाजाखा',
 'नङाब्ला',
 'नोंखौ',
 'फरायसालियाव',
 'बयबो',
 'साल',
 'बोराय',
 'होनना',
 'गाबज्रिगोन',
 'होनबाथाय',
 'नों',
 'बिगै',
 'मिनिस्रां',
 'आ',
 'बिब',
 'जंखाइनायखौ',
 'लाजि',
 'मोनना',
 'बिब',
 'खौ',
 'बिखुंआव',


In [23]:
# New Code
# From array to single array

to_string1 = ' '.join(corpus1)


In [24]:
c2 = corpus2

In [25]:
c1 = corpus1

In [26]:
corpus1 = to_string1.split(' '.join(to_string1))

In [27]:
to_string1

'मैया थांनाय सानखालि मादै मैनानि फिसाज्लाया सक्लेट बायदि बायदि गोदै मेथाय जाबोनानै हाथाइ साजादों उनाव डाक्टरनाव थांना नायनाइआवसो हाथाइ एम्फौ जाजादों होनना मोनथि मोनदोंमोन दा एम्फौ जानायखौ बख जाना बोरायबायदि हाथाइ साल ल नुबाय बाबुखौ नै आगै नोंबो बांद्राइ गोदै जाबा बोराय साल जागोन बिगै मिनिसा्ंआबो बिब सैनानि खोन्थानाय मादै मैनानि फिसाज्ला हाथाइ एमफौ जाजानाय जाथायखौ खोनानो मोनना गिख्रंना बुङो दे होनबा आब एबाराव आं बांद्राय गोदै मेथाइ खाजा जाथ ला बिब सैनायाबो खेलायनानै बुंदेरबावो दाजाखा नङाब्ला नोंखौ फरायसालियाव बयबो साल बोराय होनना गाबज्रिगोन होनबाथाय नों बिगै मिनिस्रां आ बिब जंखाइनायखौ लाजि मोनना बिब खौ बिखुंआव फंसे खेलाइनायजों बुयो नै आब आंखौ बिदि होनना दाजंखाइ बुंबायना बांद्राय गोदै जाला होनना अखानायै मादै मैनानि फिसाज्ला सोमखोरा हाथाइ साल खौ लाना फरायसालि थाङो फरायसालियाव माखासे गावनि लोगोफोरजों जंखाय जायो बोराय साल होनना सोमखोरा लाजिनाय मोननानै सासु मासु जाना मिनिस्लु जानानैल थायो मिनिस्रांआबो सोमखोर जोंनो ज फरायनाय बियो बिनि सेराव थानानै गावसिनि माखासे लोगोफोरखौ बुङो बेनिखाइनो दिनैन

In [28]:
string2 = ' '.join(corpus2)
corpus2 = string2.split(' '.join(string2))

In [29]:
string2

'दिनै गसाइगाॅव आव शनिबार हाथाइ जायो दिनै नि सानाव गोबां गामिनि गलादारफोरानो न नि गायनाइ मैगं थाइगं आरि फानफैयो एसेल राङैनो मैगं थाइगंखौबो मोनबोयो बेनिखाइनो दिनै मादै बिना आनै सोमस्रिजों लोगो नांना हाथाइआव थांगोन आबै गावदांआबो बिसोरजोंनो न नि मैगं थाइगं फानहैनो थांफागोन गमामायैनो सानजौफुनि नै 2 रिंगासोआव मादै बिना आनै सोमसि् जों लोगोसे आबै गावदांआबो मैगं थाइगं फानहैनो हाथाइआव थांफायो आबै गावदांमोननि न आ गसाइगाव टाउननि बेसेबांबा गोजान जायो गामियावबो बेबादि हाथाइ गिदिर गैया खालामगा् जायगाबो गैया हारसिंयै फैनायावबो खस्थ जायो थेवो आबै गावदांआ मैगं थाइगंखौ फाफ्लियाव खे खे रुजुनना लाबोयो गाविनि उदै फिसौजोनि उदै थाइसेखौ सुफुंनो आबैनि फिसाज्ला सासेल बिहामजोआ थाम बोसोरनि सिगांनो सोरगोआव थाहैबाय दा जिनै 12 बोसोर बैसो जानाय फिसौजो जोमैया जेब्ला बिबैया हाथाइ आव मैगं थाइगं फाननो थाङो अब्ला बियो ननि खामानिखौ मावना दोनजोबो आबैआबो दिनै हाथाइआव सौहैगो् मोना गावनि जिरायगा् जायगायाव जिरायना मैगं थाइगं फाननायखौ जागायजेनो ओजों मादै बिना आनै सोमसि्मोनाबो गसाइगाँव टाउनाव गोबावजों फैनाय बेनिखानो बिसोर सानैजों 

In [30]:
corpus2

['दिनै गसाइगाॅव आव शनिबार हाथाइ जायो दिनै नि सानाव गोबां गामिनि गलादारफोरानो न नि गायनाइ मैगं थाइगं आरि फानफैयो एसेल राङैनो मैगं थाइगंखौबो मोनबोयो बेनिखाइनो दिनै मादै बिना आनै सोमस्रिजों लोगो नांना हाथाइआव थांगोन आबै गावदांआबो बिसोरजोंनो न नि मैगं थाइगं फानहैनो थांफागोन गमामायैनो सानजौफुनि नै 2 रिंगासोआव मादै बिना आनै सोमसि् जों लोगोसे आबै गावदांआबो मैगं थाइगं फानहैनो हाथाइआव थांफायो आबै गावदांमोननि न आ गसाइगाव टाउननि बेसेबांबा गोजान जायो गामियावबो बेबादि हाथाइ गिदिर गैया खालामगा् जायगाबो गैया हारसिंयै फैनायावबो खस्थ जायो थेवो आबै गावदांआ मैगं थाइगंखौ फाफ्लियाव खे खे रुजुनना लाबोयो गाविनि उदै फिसौजोनि उदै थाइसेखौ सुफुंनो आबैनि फिसाज्ला सासेल बिहामजोआ थाम बोसोरनि सिगांनो सोरगोआव थाहैबाय दा जिनै 12 बोसोर बैसो जानाय फिसौजो जोमैया जेब्ला बिबैया हाथाइ आव मैगं थाइगं फाननो थाङो अब्ला बियो ननि खामानिखौ मावना दोनजोबो आबैआबो दिनै हाथाइआव सौहैगो् मोना गावनि जिरायगा् जायगायाव जिरायना मैगं थाइगं फाननायखौ जागायजेनो ओजों मादै बिना आनै सोमसि्मोनाबो गसाइगाँव टाउनाव गोबावजों फैनाय बेनिखानो बिसोर सानैजों

In [31]:
words1 = []
for text1 in corpus1:
    for word1 in text1.split(' '):
        words1.append(word1)

words1 = set(words1)

In [32]:
# words

In [33]:
words2 = []
for text2 in corpus2:
    for word2 in text2.split(' '):
        words2.append(word2)

words2 = set(words2)

In [34]:
words2

{'/',
 '12',
 '2',
 'अब्ला',
 'आ',
 'आंखाल',
 'आदा्',
 'आनै',
 'आबै',
 'आबैआ',
 'आबैआबो',
 'आबैखौ',
 'आबैना',
 'आबैनि',
 'आबैया',
 'आरि',
 'आव',
 'उदै',
 'उनाव',
 'एसे',
 'एसेल',
 'ओंखारो',
 'ओजों',
 'खस्थ',
 'खामानिखौ',
 'खालामगा्',
 'खुलांनो',
 'खे',
 'खौ',
 'गमामायैनो',
 'गला',
 'गलादारफोरानो',
 'गलादारि',
 'गलादारियानो',
 'गसाइगाँव',
 'गसाइगाव',
 'गसाइगाॅव',
 'गामि',
 'गामिनि',
 'गामियाव',
 'गामियावबो',
 'गायनाइ',
 'गावदां',
 'गावदांआ',
 'गावदांआबो',
 'गावदांमोननि',
 'गावनि',
 'गाविनि',
 'गिदिं',
 'गिदिर',
 'गुबुन',
 'गुवार',
 'गेजेरावनो',
 'गैया',
 'गोजान',
 'गोजौ',
 'गोबां',
 'गोबावजों',
 'जागायजेनो',
 'जानाय',
 'जायगा',
 'जायगानिफा्य',
 'जायगाबो',
 'जायगायाव',
 'जायो',
 'जाहाथे',
 'जिउ',
 'जिनै',
 'जिरायगा्',
 'जिरायना',
 'जेब्ला',
 'जों',
 'जोमैखौबो',
 'जोमैया',
 'टाउनखौ',
 'टाउननि',
 'टाउनाव',
 'थफ्ला',
 'थफ्लानिफा्य',
 'थांगोन',
 'थांफागोन',
 'थांफायो',
 'थाइगं',
 'थाइगंखौ',
 'थाइगंखौबो',
 'थाइसेखौ',
 'थाखोसिम',
 'थाङो',
 'थानाय',
 'थाम',
 'थाहैबाय',
 'थेवो',
 'दंबावोमोन',
 '

In [35]:
word2int1 = {}
for i,word1 in enumerate(words1):
    word2int1[word1] = i

print(word2int1)

{'बख': 0, 'दोनथ': 1, 'अब्ला': 2, 'थांना': 3, 'होनबाथाय': 4, 'सानखालि': 5, 'जंखाय': 6, 'गिख्रंना': 7, 'दाजाखा': 8, 'मोननानै': 9, 'नोंखौ': 10, 'बुंहैयो': 11, 'बयबो': 12, 'गाबज्रिगोन': 13, 'नों': 14, 'बिनि': 15, 'बिफा': 16, 'सोमखोरनि': 17, 'मैया': 18, 'साजादों': 19, 'सासु': 20, 'माखासे': 21, 'फरायसासियाव': 22, 'फरायसालियाव': 23, 'बुंदेरबावो': 24, 'लांना': 25, 'दिनैनिफ्राय': 26, 'बिदि': 27, 'बोरायबायदि': 28, 'लाना': 29, 'बुंनायखौ': 30, 'बिसिनियाव': 31, 'बांद्राय': 32, 'सानथामसो': 33, 'आं': 34, 'सैनायाबो': 35, 'गोरोनथि': 36, 'नांबाय': 37, 'बिब': 38, 'बोराय': 39, 'दे': 40, 'थानानै': 41, 'बे': 42, 'अखानायै': 43, 'मैखोम': 44, 'एमफौ': 45, 'जाया': 46, 'गोदै': 47, 'लोगोआ': 48, 'मेथाइ': 49, 'जानायखौ': 50, 'मैखोमाबो': 51, 'सेराव': 52, 'साल': 53, 'मैखोमा': 54, 'जाथ': 55, 'खाथियाव': 56, 'जाजाना': 57, 'फरायसालि': 58, 'जानो': 59, 'होनबा': 60, 'खेलाइनायजों': 61, 'नोंसोरबो': 62, 'जाथायखौ': 63, 'फाइब': 64, 'हाथाइ': 65, 'मिनिस्लु': 66, 'बारलाङो': 67, 'फिसाज्लाया': 68, 'मिनिस्रां': 69, 'फरायनाय': 70, 'साना'

In [36]:
word2int1 = {}

for i,word1 in enumerate(words1):
    word2int1[word1] = i

sentences1 = []
for sentence1 in corpus1:
    sentences1.append(sentence1.split())

WINDOW_SIZE = 2

data1 = []
for sentence1 in sentences1:
    for idx1, word1 in enumerate(sentence1):
        for neighbor1 in sentence1[max(idx1 - WINDOW_SIZE, 0) : min(idx1 + WINDOW_SIZE, len(sentence1)) + 1] : 
            if neighbor1 != word1:
                data1.append([word1, neighbor1])

In [37]:
word2int2 = {}

for i,word2 in enumerate(words2):
    word2int2[word2] = i

sentences2 = []
for sentence2 in corpus2:
    sentences2.append(sentence2.split())

WINDOW_SIZE = 2

data2 = []
for sentence2 in sentences2:
    for idx2, word2 in enumerate(sentence2):
        for neighbor2 in sentence2[max(idx2 - WINDOW_SIZE, 0) : min(idx2 + WINDOW_SIZE, len(sentence2)) + 1] : 
            if neighbor2 != word2:
                data2.append([word2, neighbor2])

In [73]:
import pandas as pd
for text1 in corpus1:
    print(text1)

df1 = pd.DataFrame(data1, columns = ['input', 'label'])

मैया थांनाय सानखालि मादै मैनानि फिसाज्लाया सक्लेट बायदि बायदि गोदै मेथाय जाबोनानै हाथाइ साजादों उनाव डाक्टरनाव थांना नायनाइआवसो हाथाइ एम्फौ जाजादों होनना मोनथि मोनदोंमोन दा एम्फौ जानायखौ बख जाना बोरायबायदि हाथाइ साल ल नुबाय बाबुखौ नै आगै नोंबो बांद्राइ गोदै जाबा बोराय साल जागोन बिगै मिनिसा्ंआबो बिब सैनानि खोन्थानाय मादै मैनानि फिसाज्ला हाथाइ एमफौ जाजानाय जाथायखौ खोनानो मोनना गिख्रंना बुङो दे होनबा आब एबाराव आं बांद्राय गोदै मेथाइ खाजा जाथ ला बिब सैनायाबो खेलायनानै बुंदेरबावो दाजाखा नङाब्ला नोंखौ फरायसालियाव बयबो साल बोराय होनना गाबज्रिगोन होनबाथाय नों बिगै मिनिस्रां आ बिब जंखाइनायखौ लाजि मोनना बिब खौ बिखुंआव फंसे खेलाइनायजों बुयो नै आब आंखौ बिदि होनना दाजंखाइ बुंबायना बांद्राय गोदै जाला होनना अखानायै मादै मैनानि फिसाज्ला सोमखोरा हाथाइ साल खौ लाना फरायसालि थाङो फरायसालियाव माखासे गावनि लोगोफोरजों जंखाय जायो बोराय साल होनना सोमखोरा लाजिनाय मोननानै सासु मासु जाना मिनिस्लु जानानैल थायो मिनिस्रांआबो सोमखोर जोंनो ज फरायनाय बियो बिनि सेराव थानानै गावसिनि माखासे लोगोफोरखौ बुङो बेनिखाइनो दिनैनि

In [39]:
for text2 in corpus2:
    print(text2)

df2 = pd.DataFrame(data2, columns = ['input', 'label'])

दिनै गसाइगाॅव आव शनिबार हाथाइ जायो दिनै नि सानाव गोबां गामिनि गलादारफोरानो न नि गायनाइ मैगं थाइगं आरि फानफैयो एसेल राङैनो मैगं थाइगंखौबो मोनबोयो बेनिखाइनो दिनै मादै बिना आनै सोमस्रिजों लोगो नांना हाथाइआव थांगोन आबै गावदांआबो बिसोरजोंनो न नि मैगं थाइगं फानहैनो थांफागोन गमामायैनो सानजौफुनि नै 2 रिंगासोआव मादै बिना आनै सोमसि् जों लोगोसे आबै गावदांआबो मैगं थाइगं फानहैनो हाथाइआव थांफायो आबै गावदांमोननि न आ गसाइगाव टाउननि बेसेबांबा गोजान जायो गामियावबो बेबादि हाथाइ गिदिर गैया खालामगा् जायगाबो गैया हारसिंयै फैनायावबो खस्थ जायो थेवो आबै गावदांआ मैगं थाइगंखौ फाफ्लियाव खे खे रुजुनना लाबोयो गाविनि उदै फिसौजोनि उदै थाइसेखौ सुफुंनो आबैनि फिसाज्ला सासेल बिहामजोआ थाम बोसोरनि सिगांनो सोरगोआव थाहैबाय दा जिनै 12 बोसोर बैसो जानाय फिसौजो जोमैया जेब्ला बिबैया हाथाइ आव मैगं थाइगं फाननो थाङो अब्ला बियो ननि खामानिखौ मावना दोनजोबो आबैआबो दिनै हाथाइआव सौहैगो् मोना गावनि जिरायगा् जायगायाव जिरायना मैगं थाइगं फाननायखौ जागायजेनो ओजों मादै बिना आनै सोमसि्मोनाबो गसाइगाँव टाउनाव गोबावजों फैनाय बेनिखानो बिसोर सानैजों ए

In [40]:
df1.head(10)

input    label
0     मैया   थांनाय
1     मैया  सानखालि
2   थांनाय     मैया
3   थांनाय  सानखालि
4   थांनाय     मादै
5  सानखालि     मैया
6  सानखालि   थांनाय
7  सानखालि     मादै
8  सानखालि   मैनानि
9     मादै   थांनाय

In [41]:
df2.head(10)


input     label
0      दिनै  गसाइगाॅव
1      दिनै        आव
2  गसाइगाॅव      दिनै
3  गसाइगाॅव        आव
4  गसाइगाॅव    शनिबार
5        आव      दिनै
6        आव  गसाइगाॅव
7        आव    शनिबार
8        आव     हाथाइ
9    शनिबार  गसाइगाॅव

In [42]:
df1.shape

(1176, 2)

In [43]:
df2.shape

(1190, 2)

In [44]:
import tensorflow as tf
import numpy as np
import tensorflow.compat.v1 as tf
# import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

ONE_HOT_DIM1 = len(words1)

# function to convert numbers to one hot vectors
def to_one_hot_encoding(data_point_index,ONE_HOT_DIM):
    one_hot_encoding = np.zeros(ONE_HOT_DIM)
    one_hot_encoding[data_point_index] = 1
    return one_hot_encoding

X1 = [] # input word
Y1 = [] # target word

for x, y in zip(df1['input'], df1['label']):
    X1.append(to_one_hot_encoding(word2int1[ x ],ONE_HOT_DIM1))
    Y1.append(to_one_hot_encoding(word2int1[ y ],ONE_HOT_DIM1))

# convert them to numpy arrays
X_train1 = np.asarray(X1)
Y_train1 = np.asarray(Y1)

tf.compat.v1.disable_eager_execution()

# making placeholders for X_train and Y_train
x1 = tf.placeholder(tf.float32, shape=(None, ONE_HOT_DIM1))
y_label1 = tf.placeholder(tf.float32, shape=(None, ONE_HOT_DIM1))

# word embedding will be 2 dimension for 2d visualization
EMBEDDING_DIM = 2 

# hidden layer: which represents word vector eventually
W11 = tf.Variable(tf.random_normal([ONE_HOT_DIM1, EMBEDDING_DIM]))
b11 = tf.Variable(tf.random_normal([1])) #bias
hidden_layer = tf.add(tf.matmul(x1,W11), b11)

# output layer
W21 = tf.Variable(tf.random_normal([EMBEDDING_DIM, ONE_HOT_DIM1]))
b21 = tf.Variable(tf.random_normal([1]))
prediction1 = tf.nn.softmax(tf.add( tf.matmul(hidden_layer, W21), b21))

# loss function: cross entropy
loss1 = tf.reduce_mean(-tf.reduce_sum(y_label1 * tf.log(prediction1), axis=[1]))

# training operation
train_op1 = tf.train.GradientDescentOptimizer(0.05).minimize(loss1)

Instructions for updating:
non-resource variables are not supported in the long term


In [45]:
#import tensorflow as tf
#import numpy as np
#import tensorflow.compat.v1 as tf
#tf.disable_v2_behavior()

ONE_HOT_DIM2 = len(words2)

# function to convert numbers to one hot vectors
def to_one_hot_encoding(data_point_index,ONE_HOT_DIM):
    one_hot_encoding = np.zeros(ONE_HOT_DIM)
    one_hot_encoding[data_point_index] = 1
    return one_hot_encoding

X2 = [] # input word
Y2 = [] # target word

for x, y in zip(df2['input'], df2['label']):
    X2.append(to_one_hot_encoding(word2int2[ x ],ONE_HOT_DIM2))
    Y2.append(to_one_hot_encoding(word2int2[ y ],ONE_HOT_DIM2))

# convert them to numpy arrays
X_train2 = np.asarray(X2)
Y_train2 = np.asarray(Y2)

# tf.compat.v2.disable_eager_execution()

# making placeholders for X_train and Y_train
x2 = tf.placeholder(tf.float32, shape=(None, ONE_HOT_DIM2))
y_label2 = tf.placeholder(tf.float32, shape=(None, ONE_HOT_DIM2))

# word embedding will be 2 dimension for 2d visualization
EMBEDDING_DIM = 2 

# hidden layer: which represents word vector eventually
W12 = tf.Variable(tf.random_normal([ONE_HOT_DIM2, EMBEDDING_DIM]))
b12 = tf.Variable(tf.random_normal([1])) #bias
hidden_layer = tf.add(tf.matmul(x2,W12), b12)

# output layer
W22 = tf.Variable(tf.random_normal([EMBEDDING_DIM, ONE_HOT_DIM2]))
b22 = tf.Variable(tf.random_normal([1]))
prediction = tf.nn.softmax(tf.add( tf.matmul(hidden_layer, W22), b22))

# loss function: cross entropy
loss2 = tf.reduce_mean(-tf.reduce_sum(y_label2 * tf.log(prediction), axis=[1]))

# training operation
train_op2 = tf.train.GradientDescentOptimizer(0.05).minimize(loss2)

In [46]:
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)
iteration = 20000
for i in range(iteration):
    # input is X_train which is one hot encoded word
    # label is Y_train which is one hot encoded neighbor word
    sess.run(train_op1, feed_dict={x1: X_train1, y_label1: Y_train1})
    if i % 3000 == 0:
        print('iteration '+str(i)+' loss is : ', sess.run(loss1, feed_dict={x1: X_train1, y_label1: Y_train1}))

iteration 0 loss is :  6.445217
iteration 3000 loss is :  5.3166885
iteration 6000 loss is :  5.1179056
iteration 9000 loss is :  4.9609175
iteration 12000 loss is :  4.825677
iteration 15000 loss is :  4.713325
iteration 18000 loss is :  4.6212416


In [47]:
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

iteration = 20000
for i in range(iteration):
    # input is X_train which is one hot encoded word
    # label is Y_train which is one hot encoded neighbor word
    sess.run(train_op2, feed_dict={x2: X_train2, y_label2: Y_train2})
    if i % 3000 == 0:
        print('iteration '+str(i)+' loss is : ', sess.run(loss2, feed_dict={x2: X_train2, y_label2: Y_train2}))

iteration 0 loss is :  6.1524796
iteration 3000 loss is :  5.3510957
iteration 6000 loss is :  5.118696
iteration 9000 loss is :  4.959892
iteration 12000 loss is :  4.8295026
iteration 15000 loss is :  4.7125444


In [48]:
# Now the hidden layer (W1 + b1) is actually the word look up table
vectors = sess.run(W11 + b11)
print(vectors)

[[-2.2634006  -3.6288567 ]
 [-2.4412522  -2.0138295 ]
 [-0.91648126 -3.163537  ]
 [-1.7294141  -4.261669  ]
 [-2.4678073  -2.3047953 ]
 [-2.1455474  -1.850835  ]
 [-3.1181562  -1.8963101 ]
 [-3.1515276  -2.4360902 ]
 [-3.8805728  -3.3365934 ]
 [-4.6106396  -2.5568702 ]
 [-2.1014714  -2.5132098 ]
 [-1.9726722  -1.8745608 ]
 [-1.179205   -1.7836151 ]
 [-1.2467136  -1.197665  ]
 [-1.4119265  -3.009648  ]
 [-3.7801867  -3.4363577 ]
 [-2.8783197  -1.1132702 ]
 [-2.2043393  -4.284793  ]
 [-2.6944664  -3.7744954 ]
 [-2.1957629  -3.1542892 ]
 [-1.5809622  -1.2521846 ]
 [-4.3309364  -3.6991959 ]
 [-3.1594212  -3.3636384 ]
 [-2.7803862  -3.7486854 ]
 [-2.060539   -4.307815  ]
 [-3.4309382  -4.087544  ]
 [-1.8511419  -1.3475777 ]
 [-2.2793355  -3.091536  ]
 [-1.4190555  -3.1215882 ]
 [-2.8559248  -3.2777367 ]
 [-2.5863662  -1.1405953 ]
 [-2.686806   -5.2450333 ]
 [-3.3979657  -2.4375727 ]
 [-3.8129454  -0.5527406 ]
 [-2.4543204  -4.3209815 ]
 [-3.9331956  -2.3911378 ]
 [-3.778039   -2.1331441 ]
 

In [49]:
vector = sess.run(W12 + b12)
print(vector)

[[ 4.2926699e-01  6.1792827e-01]
 [-1.7670159e+00  1.7534384e-01]
 [ 3.9120340e-01  1.3222703e+00]
 [-1.2545518e+00 -1.1711799e-01]
 [-1.7170456e-01  1.9436491e-01]
 [ 1.8837705e-02 -6.5456003e-01]
 [ 1.4490086e+00  1.1131674e+00]
 [-2.6866941e+00  3.8134730e-01]
 [-3.6311767e-01  1.0355873e+00]
 [ 7.8649616e-01  1.4744419e+00]
 [ 6.9624805e-01 -8.5642226e-02]
 [ 1.0357933e+00  8.4347910e-01]
 [ 2.1293135e+00 -6.0845625e-01]
 [ 1.5461549e+00  2.3842469e-01]
 [-1.8576996e+00  3.0146086e-01]
 [ 1.1958025e-02  9.7845674e-01]
 [ 9.7843450e-01  4.9477133e-01]
 [ 1.4476932e+00 -6.2057281e-01]
 [ 1.7802295e-01  1.0449305e+00]
 [ 9.7872239e-01 -5.4305470e-01]
 [ 1.2892739e+00  5.2574611e-01]
 [-6.9783740e-02  1.0994053e+00]
 [-3.9804408e-01  7.8506851e-01]
 [ 1.1670364e+00  1.5005646e+00]
 [-5.7065952e-01 -2.2265375e-01]
 [ 2.2567794e-01  5.5137372e-01]
 [ 1.8991811e+00  1.4608766e-01]
 [ 1.2730476e+00  8.7513906e-01]
 [-7.3213345e-01 -8.0214024e-01]
 [ 7.8550208e-01 -9.5523918e-01]
 [ 8.20390

In [50]:
vectors.shape

(206, 2)

In [51]:
vector.shape

(224, 2)

In [52]:
w2v_df1 = pd.DataFrame(vectors, columns = ['x1', 'x2'])
li =list(words1)
w2v_df1['word'] = li
w2v_df1 = w2v_df1[['word', 'x1', 'x2']]
# print(w2v_df)
w2v_df1
w2v_df1.to_csv('vectors1.csv');

In [53]:
w2v_df2 = pd.DataFrame(vector, columns = ['x1', 'x2'])
li =list(words2)
w2v_df2['word'] = li
w2v_df2 = w2v_df2[['word', 'x1', 'x2']]
# print(w2v_df)
w2v_df2
w2v_df2.to_csv('vectors2.csv');

In [54]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity([vectors[4]],[vectors[1]])

array([[0.99810916]], dtype=float32)

In [55]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity([vector[4]],[vector[1]])

array([[0.7328375]], dtype=float32)

In [56]:
vectors[4]

array([-2.4678073, -2.3047953], dtype=float32)

In [57]:
vectors[2]

array([-0.91648126, -3.163537  ], dtype=float32)

In [58]:
vector[1]

array([-1.7670159 ,  0.17534384], dtype=float32)

In [59]:
vector[2]

array([0.3912034, 1.3222703], dtype=float32)

In [60]:
sentence1 = "मैनानि फिसाज्लाया गसाइगाव हाथाइाव हाथाइनि डाक्टरनाव थांदों मोन मादैजों"
sentence2 =  "सोमखोरा हाथाइाव मैगं फानो लांना समाव गादलिनना गोग्लैना हाथाइआव दुखु मोनो"

In [61]:
pre_sentenced1 = "मैनानि फिसाज्ला गसाइगाव हाथाइ हाथाइनि डाक्टरनाव थांदों मादै" 
pre_sentenced2 = "सोमखोरा हाथाइ मैगं फानो लांना समाव गादलिनना गोग्लैना हाथाइआव दुखु"

In [62]:
final_sentence1 = pre_sentenced1.split()
final_sentence2 = pre_sentenced2.split()

# print('Sen1',final_sentence1)
# print('Sen2',final_sentence2)


In [63]:
for i in final_sentence2:
  if i in c1:
    print(i)
    print(c1.index(i))

सोमखोरा
114
हाथाइ
12
लांना
242


In [64]:
for i in final_sentence2:
  if i in c2:
    print(i)
    print(c2.index(i))

हाथाइ
4
मैगं
15
हाथाइआव
32
दुखु
246


In [65]:
indx1 = []
for i in final_sentence1:
    sum=0
    if i in c1:
        indx = c1.index(i)
        print("index",indx,i)
        for k in range(0,206):
            sum += cosine_similarity([vectors[indx]],[vectors[k]])
        indx1.append(sum/206)
        print("Sum = ",sum,"and average is",sum/206)

index 4 मैनानि
Sum =  [[199.37123]] and average is [[0.96782154]]
index 51 फिसाज्ला
Sum =  [[198.5482]] and average is [[0.96382624]]
index 12 हाथाइ
Sum =  [[195.60414]] and average is [[0.94953465]]
index 15 डाक्टरनाव
Sum =  [[199.25316]] and average is [[0.9672483]]
index 3 मादै
Sum =  [[184.0048]] and average is [[0.8932272]]


In [66]:
indx2 = []
for i in final_sentence1:
    sum=0
    if i in c2:
        indx = c2.index(i)
        print("index",indx,i)
        for k in range(0,206):
            sum += cosine_similarity([vectors[indx]],[vectors[k]])
        indx2.append(sum/206)
        print("Sum = ",sum,"and average is",sum/206)

index 99 फिसाज्ला
Sum =  [[191.25127]] and average is [[0.9284042]]
index 65 गसाइगाव
Sum =  [[194.65302]] and average is [[0.94491756]]
index 4 हाथाइ
Sum =  [[199.37123]] and average is [[0.96782154]]
index 26 मादै
Sum =  [[196.98618]] and average is [[0.9562436]]


In [67]:
indx3 = []
for i in final_sentence2:
    sum=0
    if i in c1:
        indx = c1.index(i)
        print("index",indx,i)
        for k in range(0,206):
            sum += cosine_similarity([vectors[indx]],[vectors[k]])
        indx2.append(sum/206)
        print("Sum = ",sum,"and average is",sum/206)

index 114 सोमखोरा
Sum =  [[197.82271]] and average is [[0.9603044]]
index 12 हाथाइ
Sum =  [[195.60414]] and average is [[0.94953465]]
index 242 लांना


IndexError: ignored

In [68]:
vectors.shape

(206, 2)

In [69]:
len(c1)

297