<a href="https://colab.research.google.com/github/Karmabir-Brahma/ML/blob/master/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np #importing numpy library as np 

In [2]:
one_d_array = np.array([1,2,3,4,5]) #1D array of type int
print(one_d_array)

[1 2 3 4 5]


In [6]:
one_d_array_2 = np.array([1.1,2.2,3.3,4.4]) #1D array of type float
print(one_d_array_2)

[1.1 2.2 3.3 4.4]


In [16]:
two_d_array = np.array([[0,1,2],[3,4,5],[6,8,9]]) #2D array of type int
print(two_d_array[0][1])

1


In [32]:
b = np.ones((5, 3), dtype = int) #initilizing array with all ones
print(b)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [36]:
seq_num = np.arange(1,11) #Sequence of numbers from (1 to 10(11-1))
print(seq_num)

[ 1  2  3  4  5  6  7  8  9 10]


In [48]:
random_int = np.random.randint(low=1, high=51, size=(5)) #Generates random integer from range low to high and displays size number outputs
print(random_int)

[23 50 32 38 10]


In [62]:
random_float = np.random.random() #Generates random float in interval [0.0, 1.0)
print(random_float)

0.3506847200166324


## Mathematical Operations on NumPy Operands

If you want to add or subtract two arrays, linear algebra requires that the two operands have the same dimensions. Furthermore, if you want to multiply two arrays, linear algebra imposes strict rules on the dimensional compatibility of operands. Fortunately, NumPy uses a trick called [**broadcasting**](https://developers.google.com/machine-learning/glossary/#broadcasting) to virtually expand the smaller operand to dimensions compatible for linear algebra. For example, the following operation uses broadcasting to add 2.0 to the value of every item in the array created in the below:

In [63]:
arr = np.array([1,2,3,4,5])+2
print(arr)

[3 4 5 6 7]


The following operation also relies on broadcasting to multiply each cell in an array by 3:

In [64]:
arr_2 = np.array([[1,2,3],[4,5,6]])*3
print(arr_2)

[[ 3  6  9]
 [12 15 18]]


## Task 1: Create a Linear Dataset

Your goal is to create a simple dataset consisting of a single feature and a label as follows:

1. Assign a sequence of integers from 6 to 20 (inclusive) to a NumPy array named `feature`.
2. Assign 15 values to a NumPy array named `label` such that:

```
   label = (3)(feature) + 4
```
For example, the first value for `label` should be:

```
  label = (3)(6) + 4 = 22
 ```

In [65]:
feature = np.arange(6,21) # write your code here
print(feature)
label = (feature*3)+4   # write your code here
print(label)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


In [ ]:
#@title Double-click to see a possible solution to Task 1.
feature = np.arange(6, 21)
print(feature)
label = (feature * 3) + 4
print(label)

## Task 2: Add Some Noise to the Dataset

To make your dataset a little more realistic, insert a little random noise into each element of the `label` array you already created. To be more precise, modify each value assigned to `label` by adding a *different* random floating-point value between -2 and +2. 

Don't rely on broadcasting. Instead, create a `noise` array having the same dimension as `label`.

In [67]:
noise = (np.random.random([15])*4)-2    # write your code here
print(noise)
label = label+noise    # write your code here
print(label)

[-0.23295847  0.40980434 -1.52240765  1.89256782 -1.88496263  1.88943428
 -1.41987379 -1.11287534  0.69820687 -1.8595668  -0.15509623 -1.58022819
 -1.96873442  0.82123047 -1.13081466]
[21.76704153 25.40980434 26.47759235 32.89256782 32.11503737 38.88943428
 38.58012621 41.88712466 46.69820687 47.1404332  51.84490377 53.41977181
 56.03126558 61.82123047 62.86918534]


In [ ]:
#@title Double-click to see a possible solution to Task 2.

noise = (np.random.random([15]) * 4) - 2
print(noise)
label = label + noise 
print(label)