<a href="https://colab.research.google.com/github/Karmabir-Brahma/ML/blob/master/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np #importing numpy library as np 

In [2]:
one_d_array = np.array([1,2,3,4,5]) #1D array of type int
print(one_d_array)

[1 2 3 4 5]


In [6]:
one_d_array_2 = np.array([1.1,2.2,3.3,4.4]) #1D array of type float
print(one_d_array_2)

[1.1 2.2 3.3 4.4]


In [16]:
two_d_array = np.array([[0,1,2],[3,4,5],[6,8,9]]) #2D array of type int
print(two_d_array[0][1])

1


In [32]:
b = np.ones((5, 3), dtype = int) #initilizing array with all ones
print(b)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [36]:
seq_num = np.arange(1,11) #Sequence of numbers from (1 to 10(11-1))
print(seq_num)

[ 1  2  3  4  5  6  7  8  9 10]


In [48]:
random_int = np.random.randint(low=1, high=51, size=(5)) #Generates random integer from range low to high and displays size number outputs
print(random_int)

[23 50 32 38 10]


In [62]:
random_float = np.random.random() #Generates random float in interval [0.0, 1.0)
print(random_float)

0.3506847200166324


## Mathematical Operations on NumPy Operands

If you want to add or subtract two arrays, linear algebra requires that the two operands have the same dimensions. Furthermore, if you want to multiply two arrays, linear algebra imposes strict rules on the dimensional compatibility of operands. Fortunately, NumPy uses a trick called [**broadcasting**](https://developers.google.com/machine-learning/glossary/#broadcasting) to virtually expand the smaller operand to dimensions compatible for linear algebra. For example, the following operation uses broadcasting to add 2.0 to the value of every item in the array created in the below:

In [63]:
arr = np.array([1,2,3,4,5])+2
print(arr)

[3 4 5 6 7]


The following operation also relies on broadcasting to multiply each cell in an array by 3:

In [64]:
arr_2 = np.array([[1,2,3],[4,5,6]])*3
print(arr_2)

[[ 3  6  9]
 [12 15 18]]
