<a href="https://colab.research.google.com/github/Karmabir-Brahma/ML/blob/master/Teeth_and_market.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install bodotokenizer

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
corpus1 = [ 'मैया थांनाय सानखालि मादै मैनानि फिसाज्लाया , सक्लेट,  बायदि-बायदि गोदै मेथाय जाबोनानै हाथाइ साजादों । उनाव डाक्टरनाव थांना नायनाइआवसो  हाथाइ एम्फौ जाजादों होनना मोनथि मोनदोंमोन । दा एम्फौ जानायखौ बख जाना बोरायबायदि हाथाइ साल- ल नुबाय बाबुखौ । नै आगै नोंबो बांद्राइ गोदै जाबा बोराय साल जागोन ।  बिगै मिनिसा्ंआबो बिब सैनानि खोन्थानाय मादै मैनानि फिसाज्ला हाथाइ एमफौ  जाजानाय जाथायखौ खोनानो मोनना गिख्रंना बुङो - दे होनबा आब एबाराव आं बांद्राय गोदै मेथाइ (खाजा) जाथ ला । बिब सैनायाबो खेलायनानै बुंदेरबावो - दाजाखा नङाब्ला नोंखौ फरायसालियाव बयबो साल बोराय होनना गाबज्रिगोन । होनबाथाय नों ……. बिगै मिनिस्रां आ बिब जंखाइनायखौ लाजि मोनना बिब खौ बिखुंआव फंसे खेलाइनायजों बुयो , नै आब आंखौ बिदि होनना दाजंखाइ , बुंबायना बांद्राय गोदै जाला होनना । अखानायै मादै मैनानि फिसाज्ला सोमखोरा हाथाइ साल खौ लाना फरायसालि थाङो । फरायसालियाव माखासे गावनि लोगोफोरजों जंखाय जायो - बोराय साल होनना । सोमखोरा लाजिनाय मोननानै सासु- मासु जाना मिनिस्लु जानानैल थायो । मिनिस्रांआबो सोमखोर जोंनो ज फरायनाय , बियो बिनि सेराव थानानै गावसिनि माखासे लोगोफोरखौ बुङो  - बेनिखाइनो दिनैनिफ्राय नोंसोरबो बांद्राय गोदै- गोदै मेथाइ जानो नाङा,  नङाबा सोमखोर बायदि हाथाइ गनाय साल बोराय जाजागोन । बे समावनो मिनिस्रांनि बुंफुबाय थानायावनो बिसोरनि लोगोफोरनि गेजेराव सासे मैखोम होननाय लोगोआ - मिनिस्रांनि बाथ्राखौ एंब्राना बुङो - जेबो बिदि जाया , आंनो सानफ्रोम्बो जाबाय थायो नाथाय जेबो बिदि जायाखै होनना मिनिस्रां , सोमखोर आरो माखासे लोगोफोरनि मोखांआव फाइब स्टार(5star ) सक्लेट जाना दिन्थियो  । दिना थाङो   आरो फैयो , मैखोमाबो गोदै जानायखौ दोनथ आ सानफ्रोम्बो जायो । बिदियैनो सानाबो हाबथानै बारलाङो । साननै सानथामसो थाबावना एबा हाबथा मोननै आरो खावसे साननि उनाव हाथाइ साजायो मैखोमा । साना गाबख्रावबाय थानाइआव बिनि बिफा - बिमाया बेखौ डक्टर नाव लांना हाथाइ एमफौ जानायखौ बखना होयो । अखानायै मैखोमा फरायसासियाव थांना मिनिस्रां आरो सोमखोरनि खाथियाव थांना बुंहैयो - गावनि एंब्राना बुंनानै खोथा मानियैया गोरोनथि जाबाय । दिनै आंनाबो हाथाइ एमफौ जाजाबाय, थाइसे नङा ,थानै नङा थाइथाम हाथाइ एमफौ जाजाना बख नांबाय । नोंसिनि खोथा बुंनायखौ आं गनायना जानाङामोन । अब्ला बिदि जानाय नङामोन । निमाहा होदो लोगो होननानै मैखोमा बिसिनियाव खेमाहा बियो ।']

In [3]:
corpus2 = ['दिनै गसाइगाॅव आव शनिबार हाथाइ जायो । दिनै नि सानाव गोबां गामिनि गलादारफोरानो न नि गायनाइ मैगं-थाइगं आरि फानफैयो ।  एसेल राङैनो मैगं -थाइगंखौबो मोनबोयो । बेनिखाइनो दिनै मादै बिना आरो आनै सोमस्रिजों लोगो नांना हाथाइआव थांगोन । आबै गावदांआबो बिसोरजोंनो न नि मैगं थाइगं फानहैनो थांफागोन  ।गमामायैनो सानजौफुनि नै (2) रिंगासोआव मादै बिना  आरो आनै सोमसि् जों लोगोसे आबै गावदांआबो मैगं - थाइगं फानहैनो हाथाइआव थांफायो  । आबै गावदांमोननि न आ गसाइगाव टाउननि बेसेबांबा गोजान जायो ,गामियावबो बेबादि हाथाइ गिदिर गैया खालामगा् जायगाबो गैया । हारसिंयै फैनायावबो खस्थ जायो थेवो आबै गावदांआ मैगं - थाइगंखौ फाफ्लियाव खे- खे  रुजुनना लाबोयो गाविनि उदै आरो फिसौजोनि उदै थाइसेखौ सुफुंनो । आबैनि फिसाज्ला सासेल आरो बिहामजोआ थाम बोसोरनि सिगांनो सोरगोआव थाहैबाय ।   दा जिनै( 12) - बोसोर बैसो जानाय फिसौजो जोमैया, जेब्ला बिबैया हाथाइ आव मैगं- थाइगं फाननो थाङो अब्ला बियो ननि खामानिखौ मावना दोनजोबो । आबैआबो दिनै हाथाइआव सौहैगो् मोना गावनि जिरायगा् जायगायाव जिरायना मैगं - थाइगं फाननायखौ जागायजेनो । ओजों मादै बिना आरो आनै सोमसि्मोनाबो गसाइगाँव टाउनाव गोबावजों फैनाय ,बेनिखानो बिसोर सानैजों एसे गसाइगाँव टाउनखौ बेरायगो्ना ,  उनाव मैगं - थाइगं फानगा् हाथाइसिम फैफिनना आबैनि फानफैनाय मैगं निफा्यबो बाइयो आरो गुबुन जायगानिफा्य फानफैनाय गलादारि फोरनिफा्इबो मैगं लाना गिदिं फिननो नागिरो । नाथाइ आबैना मैगंआ एसे नांबाव नांगौ दंबावोमोन,  सानाबो बारा हाबदा्इआखै,  फारसेथिं आबैआ हारसिंयै मोनाबे्बाबो हारसिंयै फैफिननो  रोङा। बेनिखानो नांजोबाबाबो आबै गावदांआ थफ्ला बोनफिनना बिसोरजोंनो हाथाइनिफा्य फैपाफिननो होनना ओंखारो । बे समावनो सासे सेंगा्या आबैखौ  लाखिना आदा् थानाय मैगंखौ बायना लाजोबनो होनना मैगंफोरखौ थफ्लानिफा्य बरन होयो । सेंगा्या मैगं नायहोलां नो आबैनि गामि, आरो गामिनि हालोदफोरखौ फारि-फारि सोंना लायो । दानदिसे उनाव गामिनि हालोद आरो आंखाल खौ नुना/ मोनथि मोनना सेंगा्या दुखु मोनो आरो दानथामसोनि गेजेरावनो आबै गावदां मोननि गामियाव बेसेबांबा गुवार जायगा बायनानै सानफो्मबो हाथाइ जानाय बायदि गावनि रांजोंनो राहा दिहुनना होयो । जाहाथे   बयबो गलादारियानो गामिनि हाथाइआवनो बायदि रोखोमनि बेसाद मुवा फानना जिउ खुलांनो  होयो । दा आबै गावदांआबो बेयावनो गावनि निजा गला लुना मैगं- थाइगं फानसै , बेजोंनो फिसौजो जोमैखौबो आबैया लासै- लासैयैनो गोजौ थाखोसिम फोरोंलांनो हाबाय ।']

In [4]:
from bodotokenizer import tokenize
tokenized_sentenc1 = []
tokenized_sentence2 = []
results1 = []
results2 = []


for sen in corpus1:
    tokenized1 = tokenize(sen)
for sen in corpus2:
    tokenized2 = tokenize(sen)

In [5]:
tokenized1

'मैया थांनाय सानखालि मादै मैनानि फिसाज्लाया , सक्लेट , बायदि - बायदि गोदै मेथाय जाबोनानै हाथाइ साजादों । उनाव डाक्टरनाव थांना नायनाइआवसो हाथाइ एम्फौ जाजादों होनना मोनथि मोनदोंमोन । दा एम्फौ जानायखौ बख जाना बोरायबायदि हाथाइ साल - ल नुबाय बाबुखौ । नै आगै नोंबो बांद्राइ गोदै जाबा बोराय साल जागोन । बिगै मिनिसा्ंआबो बिब सैनानि खोन्थानाय मादै मैनानि फिसाज्ला हाथाइ एमफौ जाजानाय जाथायखौ खोनानो मोनना गिख्रंना बुङो - दे होनबा आब एबाराव आं बांद्राय गोदै मेथाइ ( खाजा ) जाथ ला । बिब सैनायाबो खेलायनानै बुंदेरबावो - दाजाखा नङाब्ला नोंखौ फरायसालियाव बयबो साल बोराय होनना गाबज्रिगोन । होनबाथाय नों …… . बिगै मिनिस्रां आ बिब जंखाइनायखौ लाजि मोनना बिब खौ बिखुंआव फंसे खेलाइनायजों बुयो , नै आब आंखौ बिदि होनना दाजंखाइ , बुंबायना बांद्राय गोदै जाला होनना । अखानायै मादै मैनानि फिसाज्ला सोमखोरा हाथाइ साल खौ लाना फरायसालि थाङो । फरायसालियाव माखासे गावनि लोगोफोरजों जंखाय जायो - बोराय साल होनना । सोमखोरा लाजिनाय मोननानै सासु - मासु जाना मिनिस्लु जानानैल थायो । मिनिस्रांआबो सोमखोर जोंनो ज फरायनाय , बियो बिनि सेराव थ

In [6]:
tokenized2

'दिनै गसाइगाॅव आव शनिबार हाथाइ जायो । दिनै नि सानाव गोबां गामिनि गलादारफोरानो न नि गायनाइ मैगं - थाइगं आरि फानफैयो । एसेल राङैनो मैगं - थाइगंखौबो मोनबोयो । बेनिखाइनो दिनै मादै बिना आरो आनै सोमस्रिजों लोगो नांना हाथाइआव थांगोन । आबै गावदांआबो बिसोरजोंनो न नि मैगं थाइगं फानहैनो थांफागोन । गमामायैनो सानजौफुनि नै ( 2 ) रिंगासोआव मादै बिना आरो आनै सोमसि् जों लोगोसे आबै गावदांआबो मैगं - थाइगं फानहैनो हाथाइआव थांफायो । आबै गावदांमोननि न आ गसाइगाव टाउननि बेसेबांबा गोजान जायो , गामियावबो बेबादि हाथाइ गिदिर गैया खालामगा् जायगाबो गैया । हारसिंयै फैनायावबो खस्थ जायो थेवो आबै गावदांआ मैगं - थाइगंखौ फाफ्लियाव खे - खे रुजुनना लाबोयो गाविनि उदै आरो फिसौजोनि उदै थाइसेखौ सुफुंनो । आबैनि फिसाज्ला सासेल आरो बिहामजोआ थाम बोसोरनि सिगांनो सोरगोआव थाहैबाय । दा जिनै ( 12 ) - बोसोर बैसो जानाय फिसौजो जोमैया , जेब्ला बिबैया हाथाइ आव मैगं - थाइगं फाननो थाङो अब्ला बियो ननि खामानिखौ मावना दोनजोबो । आबैआबो दिनै हाथाइआव सौहैगो् मोना गावनि जिरायगा् जायगायाव जिरायना मैगं - थाइगं फाननायखौ जागायजेनो । ओजों मादै बिना आरो आ

In [7]:
# Existing Code
# def remove_punctuation(corpus):
#     punctuations = [',' , '।', '(',')', '-', '……','.', "'", ]
#     results = []
#     for text in corpus:
#         tmp = text.split()
#         print(tmp)
#         for punctuation in punctuations:
#             if punctuation in tmp:
#                 tmp.remove(punctuation)
#         results.append(" ".join(tmp))
    
#     return results

In [8]:
# Remove Punctuation
def remove_punctuation(corpus):
    punctuations = [',' , '।', '(',')', '-', '……','.', "'", ]
    results = []

    sentences = corpus.split()
#     print(sentences)
    for sen in sentences:
        if sen not in punctuations:
            results.append(sen)
    return results

In [11]:
corpus1 = remove_punctuation(tokenized1)

In [13]:
corpus1

['मैया',
 'थांनाय',
 'सानखालि',
 'मादै',
 'मैनानि',
 'फिसाज्लाया',
 'सक्लेट',
 'बायदि',
 'बायदि',
 'गोदै',
 'मेथाय',
 'जाबोनानै',
 'हाथाइ',
 'साजादों',
 'उनाव',
 'डाक्टरनाव',
 'थांना',
 'नायनाइआवसो',
 'हाथाइ',
 'एम्फौ',
 'जाजादों',
 'होनना',
 'मोनथि',
 'मोनदोंमोन',
 'दा',
 'एम्फौ',
 'जानायखौ',
 'बख',
 'जाना',
 'बोरायबायदि',
 'हाथाइ',
 'साल',
 'ल',
 'नुबाय',
 'बाबुखौ',
 'नै',
 'आगै',
 'नोंबो',
 'बांद्राइ',
 'गोदै',
 'जाबा',
 'बोराय',
 'साल',
 'जागोन',
 'बिगै',
 'मिनिसा्ंआबो',
 'बिब',
 'सैनानि',
 'खोन्थानाय',
 'मादै',
 'मैनानि',
 'फिसाज्ला',
 'हाथाइ',
 'एमफौ',
 'जाजानाय',
 'जाथायखौ',
 'खोनानो',
 'मोनना',
 'गिख्रंना',
 'बुङो',
 'दे',
 'होनबा',
 'आब',
 'एबाराव',
 'आं',
 'बांद्राय',
 'गोदै',
 'मेथाइ',
 'खाजा',
 'जाथ',
 'ला',
 'बिब',
 'सैनायाबो',
 'खेलायनानै',
 'बुंदेरबावो',
 'दाजाखा',
 'नङाब्ला',
 'नोंखौ',
 'फरायसालियाव',
 'बयबो',
 'साल',
 'बोराय',
 'होनना',
 'गाबज्रिगोन',
 'होनबाथाय',
 'नों',
 'बिगै',
 'मिनिस्रां',
 'आ',
 'बिब',
 'जंखाइनायखौ',
 'लाजि',
 'मोनना',
 'बिब',
 'खौ',
 'बिखुंआव',


In [14]:
corpus2 = remove_punctuation(tokenized2)

In [16]:
corpus2

['दिनै',
 'गसाइगाॅव',
 'आव',
 'शनिबार',
 'हाथाइ',
 'जायो',
 'दिनै',
 'नि',
 'सानाव',
 'गोबां',
 'गामिनि',
 'गलादारफोरानो',
 'न',
 'नि',
 'गायनाइ',
 'मैगं',
 'थाइगं',
 'आरि',
 'फानफैयो',
 'एसेल',
 'राङैनो',
 'मैगं',
 'थाइगंखौबो',
 'मोनबोयो',
 'बेनिखाइनो',
 'दिनै',
 'मादै',
 'बिना',
 'आरो',
 'आनै',
 'सोमस्रिजों',
 'लोगो',
 'नांना',
 'हाथाइआव',
 'थांगोन',
 'आबै',
 'गावदांआबो',
 'बिसोरजोंनो',
 'न',
 'नि',
 'मैगं',
 'थाइगं',
 'फानहैनो',
 'थांफागोन',
 'गमामायैनो',
 'सानजौफुनि',
 'नै',
 '2',
 'रिंगासोआव',
 'मादै',
 'बिना',
 'आरो',
 'आनै',
 'सोमसि्',
 'जों',
 'लोगोसे',
 'आबै',
 'गावदांआबो',
 'मैगं',
 'थाइगं',
 'फानहैनो',
 'हाथाइआव',
 'थांफायो',
 'आबै',
 'गावदांमोननि',
 'न',
 'आ',
 'गसाइगाव',
 'टाउननि',
 'बेसेबांबा',
 'गोजान',
 'जायो',
 'गामियावबो',
 'बेबादि',
 'हाथाइ',
 'गिदिर',
 'गैया',
 'खालामगा्',
 'जायगाबो',
 'गैया',
 'हारसिंयै',
 'फैनायावबो',
 'खस्थ',
 'जायो',
 'थेवो',
 'आबै',
 'गावदांआ',
 'मैगं',
 'थाइगंखौ',
 'फाफ्लियाव',
 'खे',
 'खे',
 'रुजुनना',
 'लाबोयो',
 'गाविनि',
 'उदै',
 'आरो',
 '

In [17]:
# Existing Code
# def remove_stop_words(corpus):
#     stop_words = ['आरो', 'ए ', 'एबा', 'एबा', 'जेरैनों', 'सोर', ' बब']
#     results = []
#     for text in corpus:
#         tmp = text.split(' ')
#         for stop_word in stop_words:
#             if stop_word in tmp:
#                 tmp.remove(stop_word)
#         results.append(" ".join(tmp))
    
#     return results

In [18]:
# New Code
# Remove Stop Words
def remove_stop_words(corpus):
    stop_words = ['आरो', 'ए ', 'एबा', 'जेरैनों', 'सोर', 'बब']
    results = []
    stop = []

    for sen in corpus:
        if sen not in stop_words:
            results.append(sen)
    return results

In [19]:
corpus1 = remove_stop_words(corpus1)

In [20]:
corpus2 = remove_stop_words(corpus2)

In [23]:
corpus1

['मैया',
 'थांनाय',
 'सानखालि',
 'मादै',
 'मैनानि',
 'फिसाज्लाया',
 'सक्लेट',
 'बायदि',
 'बायदि',
 'गोदै',
 'मेथाय',
 'जाबोनानै',
 'हाथाइ',
 'साजादों',
 'उनाव',
 'डाक्टरनाव',
 'थांना',
 'नायनाइआवसो',
 'हाथाइ',
 'एम्फौ',
 'जाजादों',
 'होनना',
 'मोनथि',
 'मोनदोंमोन',
 'दा',
 'एम्फौ',
 'जानायखौ',
 'बख',
 'जाना',
 'बोरायबायदि',
 'हाथाइ',
 'साल',
 'ल',
 'नुबाय',
 'बाबुखौ',
 'नै',
 'आगै',
 'नोंबो',
 'बांद्राइ',
 'गोदै',
 'जाबा',
 'बोराय',
 'साल',
 'जागोन',
 'बिगै',
 'मिनिसा्ंआबो',
 'बिब',
 'सैनानि',
 'खोन्थानाय',
 'मादै',
 'मैनानि',
 'फिसाज्ला',
 'हाथाइ',
 'एमफौ',
 'जाजानाय',
 'जाथायखौ',
 'खोनानो',
 'मोनना',
 'गिख्रंना',
 'बुङो',
 'दे',
 'होनबा',
 'आब',
 'एबाराव',
 'आं',
 'बांद्राय',
 'गोदै',
 'मेथाइ',
 'खाजा',
 'जाथ',
 'ला',
 'बिब',
 'सैनायाबो',
 'खेलायनानै',
 'बुंदेरबावो',
 'दाजाखा',
 'नङाब्ला',
 'नोंखौ',
 'फरायसालियाव',
 'बयबो',
 'साल',
 'बोराय',
 'होनना',
 'गाबज्रिगोन',
 'होनबाथाय',
 'नों',
 'बिगै',
 'मिनिस्रां',
 'आ',
 'बिब',
 'जंखाइनायखौ',
 'लाजि',
 'मोनना',
 'बिब',
 'खौ',
 'बिखुंआव',


In [24]:
corpus2

['दिनै',
 'गसाइगाॅव',
 'आव',
 'शनिबार',
 'हाथाइ',
 'जायो',
 'दिनै',
 'नि',
 'सानाव',
 'गोबां',
 'गामिनि',
 'गलादारफोरानो',
 'न',
 'नि',
 'गायनाइ',
 'मैगं',
 'थाइगं',
 'आरि',
 'फानफैयो',
 'एसेल',
 'राङैनो',
 'मैगं',
 'थाइगंखौबो',
 'मोनबोयो',
 'बेनिखाइनो',
 'दिनै',
 'मादै',
 'बिना',
 'आनै',
 'सोमस्रिजों',
 'लोगो',
 'नांना',
 'हाथाइआव',
 'थांगोन',
 'आबै',
 'गावदांआबो',
 'बिसोरजोंनो',
 'न',
 'नि',
 'मैगं',
 'थाइगं',
 'फानहैनो',
 'थांफागोन',
 'गमामायैनो',
 'सानजौफुनि',
 'नै',
 '2',
 'रिंगासोआव',
 'मादै',
 'बिना',
 'आनै',
 'सोमसि्',
 'जों',
 'लोगोसे',
 'आबै',
 'गावदांआबो',
 'मैगं',
 'थाइगं',
 'फानहैनो',
 'हाथाइआव',
 'थांफायो',
 'आबै',
 'गावदांमोननि',
 'न',
 'आ',
 'गसाइगाव',
 'टाउननि',
 'बेसेबांबा',
 'गोजान',
 'जायो',
 'गामियावबो',
 'बेबादि',
 'हाथाइ',
 'गिदिर',
 'गैया',
 'खालामगा्',
 'जायगाबो',
 'गैया',
 'हारसिंयै',
 'फैनायावबो',
 'खस्थ',
 'जायो',
 'थेवो',
 'आबै',
 'गावदांआ',
 'मैगं',
 'थाइगंखौ',
 'फाफ्लियाव',
 'खे',
 'खे',
 'रुजुनना',
 'लाबोयो',
 'गाविनि',
 'उदै',
 'फिसौजोनि',
 'उदै',
 'थाइ

In [25]:
# New Code
# From array to single array

to_string1 = ' '.join(corpus1)


In [26]:
c2 = corpus2

In [27]:
c1 = corpus1

In [28]:
corpus1 = to_string1.split(' '.join(to_string1))

In [29]:
to_string1

'मैया थांनाय सानखालि मादै मैनानि फिसाज्लाया सक्लेट बायदि बायदि गोदै मेथाय जाबोनानै हाथाइ साजादों उनाव डाक्टरनाव थांना नायनाइआवसो हाथाइ एम्फौ जाजादों होनना मोनथि मोनदोंमोन दा एम्फौ जानायखौ बख जाना बोरायबायदि हाथाइ साल ल नुबाय बाबुखौ नै आगै नोंबो बांद्राइ गोदै जाबा बोराय साल जागोन बिगै मिनिसा्ंआबो बिब सैनानि खोन्थानाय मादै मैनानि फिसाज्ला हाथाइ एमफौ जाजानाय जाथायखौ खोनानो मोनना गिख्रंना बुङो दे होनबा आब एबाराव आं बांद्राय गोदै मेथाइ खाजा जाथ ला बिब सैनायाबो खेलायनानै बुंदेरबावो दाजाखा नङाब्ला नोंखौ फरायसालियाव बयबो साल बोराय होनना गाबज्रिगोन होनबाथाय नों बिगै मिनिस्रां आ बिब जंखाइनायखौ लाजि मोनना बिब खौ बिखुंआव फंसे खेलाइनायजों बुयो नै आब आंखौ बिदि होनना दाजंखाइ बुंबायना बांद्राय गोदै जाला होनना अखानायै मादै मैनानि फिसाज्ला सोमखोरा हाथाइ साल खौ लाना फरायसालि थाङो फरायसालियाव माखासे गावनि लोगोफोरजों जंखाय जायो बोराय साल होनना सोमखोरा लाजिनाय मोननानै सासु मासु जाना मिनिस्लु जानानैल थायो मिनिस्रांआबो सोमखोर जोंनो ज फरायनाय बियो बिनि सेराव थानानै गावसिनि माखासे लोगोफोरखौ बुङो बेनिखाइनो दिनैन

In [30]:
string2 = ' '.join(corpus2)
corpus2 = string2.split(' '.join(string2))

In [31]:
string2

'दिनै गसाइगाॅव आव शनिबार हाथाइ जायो दिनै नि सानाव गोबां गामिनि गलादारफोरानो न नि गायनाइ मैगं थाइगं आरि फानफैयो एसेल राङैनो मैगं थाइगंखौबो मोनबोयो बेनिखाइनो दिनै मादै बिना आनै सोमस्रिजों लोगो नांना हाथाइआव थांगोन आबै गावदांआबो बिसोरजोंनो न नि मैगं थाइगं फानहैनो थांफागोन गमामायैनो सानजौफुनि नै 2 रिंगासोआव मादै बिना आनै सोमसि् जों लोगोसे आबै गावदांआबो मैगं थाइगं फानहैनो हाथाइआव थांफायो आबै गावदांमोननि न आ गसाइगाव टाउननि बेसेबांबा गोजान जायो गामियावबो बेबादि हाथाइ गिदिर गैया खालामगा् जायगाबो गैया हारसिंयै फैनायावबो खस्थ जायो थेवो आबै गावदांआ मैगं थाइगंखौ फाफ्लियाव खे खे रुजुनना लाबोयो गाविनि उदै फिसौजोनि उदै थाइसेखौ सुफुंनो आबैनि फिसाज्ला सासेल बिहामजोआ थाम बोसोरनि सिगांनो सोरगोआव थाहैबाय दा जिनै 12 बोसोर बैसो जानाय फिसौजो जोमैया जेब्ला बिबैया हाथाइ आव मैगं थाइगं फाननो थाङो अब्ला बियो ननि खामानिखौ मावना दोनजोबो आबैआबो दिनै हाथाइआव सौहैगो् मोना गावनि जिरायगा् जायगायाव जिरायना मैगं थाइगं फाननायखौ जागायजेनो ओजों मादै बिना आनै सोमसि्मोनाबो गसाइगाँव टाउनाव गोबावजों फैनाय बेनिखानो बिसोर सानैजों 

In [32]:
corpus2

['दिनै गसाइगाॅव आव शनिबार हाथाइ जायो दिनै नि सानाव गोबां गामिनि गलादारफोरानो न नि गायनाइ मैगं थाइगं आरि फानफैयो एसेल राङैनो मैगं थाइगंखौबो मोनबोयो बेनिखाइनो दिनै मादै बिना आनै सोमस्रिजों लोगो नांना हाथाइआव थांगोन आबै गावदांआबो बिसोरजोंनो न नि मैगं थाइगं फानहैनो थांफागोन गमामायैनो सानजौफुनि नै 2 रिंगासोआव मादै बिना आनै सोमसि् जों लोगोसे आबै गावदांआबो मैगं थाइगं फानहैनो हाथाइआव थांफायो आबै गावदांमोननि न आ गसाइगाव टाउननि बेसेबांबा गोजान जायो गामियावबो बेबादि हाथाइ गिदिर गैया खालामगा् जायगाबो गैया हारसिंयै फैनायावबो खस्थ जायो थेवो आबै गावदांआ मैगं थाइगंखौ फाफ्लियाव खे खे रुजुनना लाबोयो गाविनि उदै फिसौजोनि उदै थाइसेखौ सुफुंनो आबैनि फिसाज्ला सासेल बिहामजोआ थाम बोसोरनि सिगांनो सोरगोआव थाहैबाय दा जिनै 12 बोसोर बैसो जानाय फिसौजो जोमैया जेब्ला बिबैया हाथाइ आव मैगं थाइगं फाननो थाङो अब्ला बियो ननि खामानिखौ मावना दोनजोबो आबैआबो दिनै हाथाइआव सौहैगो् मोना गावनि जिरायगा् जायगायाव जिरायना मैगं थाइगं फाननायखौ जागायजेनो ओजों मादै बिना आनै सोमसि्मोनाबो गसाइगाँव टाउनाव गोबावजों फैनाय बेनिखानो बिसोर सानैजों

In [105]:
words1 = []
for text1 in corpus1:
    for word1 in text1.split(' '):
        words1.append(word1)
words1 = set(words1)

In [34]:
words1

{'5star',
 'अखानायै',
 'अब्ला',
 'आ',
 'आं',
 'आंखौ',
 'आंनाबो',
 'आंनो',
 'आगै',
 'आब',
 'उनाव',
 'एंब्राना',
 'एबाराव',
 'एमफौ',
 'एम्फौ',
 'खाजा',
 'खाथियाव',
 'खावसे',
 'खेमाहा',
 'खेलाइनायजों',
 'खेलायनानै',
 'खोथा',
 'खोनानो',
 'खोन्थानाय',
 'खौ',
 'गनाय',
 'गनायना',
 'गाबख्रावबाय',
 'गाबज्रिगोन',
 'गावनि',
 'गावसिनि',
 'गिख्रंना',
 'गेजेराव',
 'गोदै',
 'गोरोनथि',
 'ज',
 'जंखाइनायखौ',
 'जंखाय',
 'जागोन',
 'जाजागोन',
 'जाजादों',
 'जाजाना',
 'जाजानाय',
 'जाजाबाय',
 'जाथ',
 'जाथायखौ',
 'जाना',
 'जानाङामोन',
 'जानानैल',
 'जानाय',
 'जानायखौ',
 'जानो',
 'जाबा',
 'जाबाय',
 'जाबोनानै',
 'जाया',
 'जायाखै',
 'जायो',
 'जाला',
 'जेबो',
 'जोंनो',
 'डक्टर',
 'डाक्टरनाव',
 'थांना',
 'थांनाय',
 'थाइथाम',
 'थाइसे',
 'थाङो',
 'थानाइआव',
 'थानानै',
 'थानायावनो',
 'थानै',
 'थाबावना',
 'थायो',
 'दा',
 'दाजंखाइ',
 'दाजाखा',
 'दिना',
 'दिनै',
 'दिनैनिफ्राय',
 'दिन्थियो',
 'दे',
 'दोनथ',
 'नङा',
 'नङाबा',
 'नङाब्ला',
 'नङामोन',
 'नांबाय',
 'नाङा',
 'नाथाय',
 'नायनाइआवसो',
 'नाव',
 'निमाहा',
 'नुबाय',
 '

In [35]:
words2 = []
for text2 in corpus2:
    for word2 in text2.split(' '):
        words2.append(word2)

words2 = set(words2)

In [37]:
words2

{'/',
 '12',
 '2',
 'अब्ला',
 'आ',
 'आंखाल',
 'आदा्',
 'आनै',
 'आबै',
 'आबैआ',
 'आबैआबो',
 'आबैखौ',
 'आबैना',
 'आबैनि',
 'आबैया',
 'आरि',
 'आव',
 'उदै',
 'उनाव',
 'एसे',
 'एसेल',
 'ओंखारो',
 'ओजों',
 'खस्थ',
 'खामानिखौ',
 'खालामगा्',
 'खुलांनो',
 'खे',
 'खौ',
 'गमामायैनो',
 'गला',
 'गलादारफोरानो',
 'गलादारि',
 'गलादारियानो',
 'गसाइगाँव',
 'गसाइगाव',
 'गसाइगाॅव',
 'गामि',
 'गामिनि',
 'गामियाव',
 'गामियावबो',
 'गायनाइ',
 'गावदां',
 'गावदांआ',
 'गावदांआबो',
 'गावदांमोननि',
 'गावनि',
 'गाविनि',
 'गिदिं',
 'गिदिर',
 'गुबुन',
 'गुवार',
 'गेजेरावनो',
 'गैया',
 'गोजान',
 'गोजौ',
 'गोबां',
 'गोबावजों',
 'जागायजेनो',
 'जानाय',
 'जायगा',
 'जायगानिफा्य',
 'जायगाबो',
 'जायगायाव',
 'जायो',
 'जाहाथे',
 'जिउ',
 'जिनै',
 'जिरायगा्',
 'जिरायना',
 'जेब्ला',
 'जों',
 'जोमैखौबो',
 'जोमैया',
 'टाउनखौ',
 'टाउननि',
 'टाउनाव',
 'थफ्ला',
 'थफ्लानिफा्य',
 'थांगोन',
 'थांफागोन',
 'थांफायो',
 'थाइगं',
 'थाइगंखौ',
 'थाइगंखौबो',
 'थाइसेखौ',
 'थाखोसिम',
 'थाङो',
 'थानाय',
 'थाम',
 'थाहैबाय',
 'थेवो',
 'दंबावोमोन',
 '

In [38]:
word2int1 = {}
for i,word1 in enumerate(words1):
    word2int1[word1] = i

print(word2int1)

{'माखासे': 0, 'नाथाय': 1, 'आं': 2, 'फरायसासियाव': 3, 'नङा': 4, 'बेखौ': 5, 'थायो': 6, 'लोगोफोरजों': 7, 'जायो': 8, 'जानो': 9, 'सानफ्रोम्बो': 10, 'थानायावनो': 11, 'नों': 12, 'गनायना': 13, 'बिखुंआव': 14, 'मैनानि': 15, 'मिनिसा्ंआबो': 16, 'बोराय': 17, 'जाया': 18, 'जाथ': 19, 'नुबाय': 20, 'बांद्राय': 21, 'दिनैनिफ्राय': 22, 'एंब्राना': 23, 'मासु': 24, 'बिगै': 25, 'नोंसिनि': 26, 'आंखौ': 27, 'खाजा': 28, 'नायनाइआवसो': 29, 'बेनिखाइनो': 30, 'मैखोमाबो': 31, 'जायाखै': 32, 'होदो': 33, 'बिब': 34, 'नाव': 35, 'गोरोनथि': 36, 'दोनथ': 37, 'दाजाखा': 38, 'फरायनाय': 39, 'जेबो': 40, 'फरायसालियाव': 41, 'लोगोफोरखौ': 42, 'फंसे': 43, 'मेथाय': 44, 'होयो': 45, 'फिसाज्लाया': 46, 'खेमाहा': 47, 'मादै': 48, 'खोन्थानाय': 49, 'गाबज्रिगोन': 50, 'फाइब': 51, 'जाजागोन': 52, 'खेलाइनायजों': 53, 'लोगोआ': 54, 'बिमाया': 55, 'जानाङामोन': 56, 'नङामोन': 57, 'मिनिस्लु': 58, 'नाङा': 59, 'बयबो': 60, 'जाथायखौ': 61, 'थानानै': 62, 'जंखाइनायखौ': 63, 'मोनदोंमोन': 64, 'मोखांआव': 65, 'नोंखौ': 66, 'गेजेराव': 67, 'साजायो': 68, 'हाबथा': 69, 'फरायसा

In [39]:
word2int1 = {}

for i,word1 in enumerate(words1):
    word2int1[word1] = i

sentences1 = []
for sentence1 in corpus1:
    sentences1.append(sentence1.split())

WINDOW_SIZE = 2

data1 = []
for sentence1 in sentences1:
    for idx1, word1 in enumerate(sentence1):
        for neighbor1 in sentence1[max(idx1 - WINDOW_SIZE, 0) : min(idx1 + WINDOW_SIZE, len(sentence1)) + 1] : 
            if neighbor1 != word1:
                data1.append([word1, neighbor1])

In [40]:
word2int2 = {}

for i,word2 in enumerate(words2):
    word2int2[word2] = i

sentences2 = []
for sentence2 in corpus2:
    sentences2.append(sentence2.split())

WINDOW_SIZE = 2

data2 = []
for sentence2 in sentences2:
    for idx2, word2 in enumerate(sentence2):
        for neighbor2 in sentence2[max(idx2 - WINDOW_SIZE, 0) : min(idx2 + WINDOW_SIZE, len(sentence2)) + 1] : 
            if neighbor2 != word2:
                data2.append([word2, neighbor2])

In [41]:
import pandas as pd
for text1 in corpus1:
    print(text1)

df1 = pd.DataFrame(data1, columns = ['input', 'label'])

मैया थांनाय सानखालि मादै मैनानि फिसाज्लाया सक्लेट बायदि बायदि गोदै मेथाय जाबोनानै हाथाइ साजादों उनाव डाक्टरनाव थांना नायनाइआवसो हाथाइ एम्फौ जाजादों होनना मोनथि मोनदोंमोन दा एम्फौ जानायखौ बख जाना बोरायबायदि हाथाइ साल ल नुबाय बाबुखौ नै आगै नोंबो बांद्राइ गोदै जाबा बोराय साल जागोन बिगै मिनिसा्ंआबो बिब सैनानि खोन्थानाय मादै मैनानि फिसाज्ला हाथाइ एमफौ जाजानाय जाथायखौ खोनानो मोनना गिख्रंना बुङो दे होनबा आब एबाराव आं बांद्राय गोदै मेथाइ खाजा जाथ ला बिब सैनायाबो खेलायनानै बुंदेरबावो दाजाखा नङाब्ला नोंखौ फरायसालियाव बयबो साल बोराय होनना गाबज्रिगोन होनबाथाय नों बिगै मिनिस्रां आ बिब जंखाइनायखौ लाजि मोनना बिब खौ बिखुंआव फंसे खेलाइनायजों बुयो नै आब आंखौ बिदि होनना दाजंखाइ बुंबायना बांद्राय गोदै जाला होनना अखानायै मादै मैनानि फिसाज्ला सोमखोरा हाथाइ साल खौ लाना फरायसालि थाङो फरायसालियाव माखासे गावनि लोगोफोरजों जंखाय जायो बोराय साल होनना सोमखोरा लाजिनाय मोननानै सासु मासु जाना मिनिस्लु जानानैल थायो मिनिस्रांआबो सोमखोर जोंनो ज फरायनाय बियो बिनि सेराव थानानै गावसिनि माखासे लोगोफोरखौ बुङो बेनिखाइनो दिनैनि

In [42]:
for text2 in corpus2:
    print(text2)

df2 = pd.DataFrame(data2, columns = ['input', 'label'])

दिनै गसाइगाॅव आव शनिबार हाथाइ जायो दिनै नि सानाव गोबां गामिनि गलादारफोरानो न नि गायनाइ मैगं थाइगं आरि फानफैयो एसेल राङैनो मैगं थाइगंखौबो मोनबोयो बेनिखाइनो दिनै मादै बिना आनै सोमस्रिजों लोगो नांना हाथाइआव थांगोन आबै गावदांआबो बिसोरजोंनो न नि मैगं थाइगं फानहैनो थांफागोन गमामायैनो सानजौफुनि नै 2 रिंगासोआव मादै बिना आनै सोमसि् जों लोगोसे आबै गावदांआबो मैगं थाइगं फानहैनो हाथाइआव थांफायो आबै गावदांमोननि न आ गसाइगाव टाउननि बेसेबांबा गोजान जायो गामियावबो बेबादि हाथाइ गिदिर गैया खालामगा् जायगाबो गैया हारसिंयै फैनायावबो खस्थ जायो थेवो आबै गावदांआ मैगं थाइगंखौ फाफ्लियाव खे खे रुजुनना लाबोयो गाविनि उदै फिसौजोनि उदै थाइसेखौ सुफुंनो आबैनि फिसाज्ला सासेल बिहामजोआ थाम बोसोरनि सिगांनो सोरगोआव थाहैबाय दा जिनै 12 बोसोर बैसो जानाय फिसौजो जोमैया जेब्ला बिबैया हाथाइ आव मैगं थाइगं फाननो थाङो अब्ला बियो ननि खामानिखौ मावना दोनजोबो आबैआबो दिनै हाथाइआव सौहैगो् मोना गावनि जिरायगा् जायगायाव जिरायना मैगं थाइगं फाननायखौ जागायजेनो ओजों मादै बिना आनै सोमसि्मोनाबो गसाइगाँव टाउनाव गोबावजों फैनाय बेनिखानो बिसोर सानैजों ए

In [43]:
df1.head(10)

input    label
0     मैया   थांनाय
1     मैया  सानखालि
2   थांनाय     मैया
3   थांनाय  सानखालि
4   थांनाय     मादै
5  सानखालि     मैया
6  सानखालि   थांनाय
7  सानखालि     मादै
8  सानखालि   मैनानि
9     मादै   थांनाय

In [44]:
df2.head(10)


input     label
0      दिनै  गसाइगाॅव
1      दिनै        आव
2  गसाइगाॅव      दिनै
3  गसाइगाॅव        आव
4  गसाइगाॅव    शनिबार
5        आव      दिनै
6        आव  गसाइगाॅव
7        आव    शनिबार
8        आव     हाथाइ
9    शनिबार  गसाइगाॅव

In [45]:
df1.shape

(1176, 2)

In [46]:
df2.shape

(1190, 2)

In [47]:
import tensorflow as tf
import numpy as np
import tensorflow.compat.v1 as tf
# import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

ONE_HOT_DIM1 = len(words1)

# function to convert numbers to one hot vectors
def to_one_hot_encoding(data_point_index,ONE_HOT_DIM):
    one_hot_encoding = np.zeros(ONE_HOT_DIM)
    one_hot_encoding[data_point_index] = 1
    return one_hot_encoding

X1 = [] # input word
Y1 = [] # target word

for x, y in zip(df1['input'], df1['label']):
    X1.append(to_one_hot_encoding(word2int1[ x ],ONE_HOT_DIM1))
    Y1.append(to_one_hot_encoding(word2int1[ y ],ONE_HOT_DIM1))

# convert them to numpy arrays
X_train1 = np.asarray(X1)
Y_train1 = np.asarray(Y1)

tf.compat.v1.disable_eager_execution()

# making placeholders for X_train and Y_train
x1 = tf.placeholder(tf.float32, shape=(None, ONE_HOT_DIM1))
y_label1 = tf.placeholder(tf.float32, shape=(None, ONE_HOT_DIM1))

# word embedding will be 2 dimension for 2d visualization
EMBEDDING_DIM = 2 

# hidden layer: which represents word vector eventually
W11 = tf.Variable(tf.random_normal([ONE_HOT_DIM1, EMBEDDING_DIM]))
b11 = tf.Variable(tf.random_normal([1])) #bias
hidden_layer = tf.add(tf.matmul(x1,W11), b11)

# output layer
W21 = tf.Variable(tf.random_normal([EMBEDDING_DIM, ONE_HOT_DIM1]))
b21 = tf.Variable(tf.random_normal([1]))
prediction1 = tf.nn.softmax(tf.add( tf.matmul(hidden_layer, W21), b21))

# loss function: cross entropy
loss1 = tf.reduce_mean(-tf.reduce_sum(y_label1 * tf.log(prediction1), axis=[1]))

# training operation
train_op1 = tf.train.GradientDescentOptimizer(0.05).minimize(loss1)

Instructions for updating:
non-resource variables are not supported in the long term


In [48]:
#import tensorflow as tf
#import numpy as np
#import tensorflow.compat.v1 as tf
#tf.disable_v2_behavior()

ONE_HOT_DIM2 = len(words2)

# function to convert numbers to one hot vectors
def to_one_hot_encoding(data_point_index,ONE_HOT_DIM):
    one_hot_encoding = np.zeros(ONE_HOT_DIM)
    one_hot_encoding[data_point_index] = 1
    return one_hot_encoding

X2 = [] # input word
Y2 = [] # target word

for x, y in zip(df2['input'], df2['label']):
    X2.append(to_one_hot_encoding(word2int2[ x ],ONE_HOT_DIM2))
    Y2.append(to_one_hot_encoding(word2int2[ y ],ONE_HOT_DIM2))

# convert them to numpy arrays
X_train2 = np.asarray(X2)
Y_train2 = np.asarray(Y2)

# tf.compat.v2.disable_eager_execution()

# making placeholders for X_train and Y_train
x2 = tf.placeholder(tf.float32, shape=(None, ONE_HOT_DIM2))
y_label2 = tf.placeholder(tf.float32, shape=(None, ONE_HOT_DIM2))

# word embedding will be 2 dimension for 2d visualization
EMBEDDING_DIM = 2 

# hidden layer: which represents word vector eventually
W12 = tf.Variable(tf.random_normal([ONE_HOT_DIM2, EMBEDDING_DIM]))
b12 = tf.Variable(tf.random_normal([1])) #bias
hidden_layer = tf.add(tf.matmul(x2,W12), b12)

# output layer
W22 = tf.Variable(tf.random_normal([EMBEDDING_DIM, ONE_HOT_DIM2]))
b22 = tf.Variable(tf.random_normal([1]))
prediction = tf.nn.softmax(tf.add( tf.matmul(hidden_layer, W22), b22))

# loss function: cross entropy
loss2 = tf.reduce_mean(-tf.reduce_sum(y_label2 * tf.log(prediction), axis=[1]))

# training operation
train_op2 = tf.train.GradientDescentOptimizer(0.05).minimize(loss2)

In [49]:
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)
iteration = 20000
for i in range(iteration):
    # input is X_train which is one hot encoded word
    # label is Y_train which is one hot encoded neighbor word
    sess.run(train_op1, feed_dict={x1: X_train1, y_label1: Y_train1})
    if i % 3000 == 0:
        print('iteration '+str(i)+' loss is : ', sess.run(loss1, feed_dict={x1: X_train1, y_label1: Y_train1}))

iteration 0 loss is :  7.4439416
iteration 3000 loss is :  5.2659993
iteration 6000 loss is :  5.0354204
iteration 9000 loss is :  4.876879
iteration 12000 loss is :  4.750671
iteration 15000 loss is :  4.646324
iteration 18000 loss is :  4.5599446


In [50]:
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

iteration = 20000
for i in range(iteration):
    # input is X_train which is one hot encoded word
    # label is Y_train which is one hot encoded neighbor word
    sess.run(train_op2, feed_dict={x2: X_train2, y_label2: Y_train2})
    if i % 3000 == 0:
        print('iteration '+str(i)+' loss is : ', sess.run(loss2, feed_dict={x2: X_train2, y_label2: Y_train2}))

iteration 0 loss is :  6.742456
iteration 3000 loss is :  5.402404
iteration 6000 loss is :  5.134719
iteration 9000 loss is :  4.9385543
iteration 12000 loss is :  4.786964
iteration 15000 loss is :  4.668454
iteration 18000 loss is :  4.5712247


In [51]:
# Now the hidden layer (W1 + b1) is actually the word look up table
vectors = sess.run(W11 + b11)
print(vectors)

[[-1.0295318  -0.0100139 ]
 [-0.05943319  1.3185717 ]
 [ 1.474749   -2.6631548 ]
 [-1.2961512   1.0230292 ]
 [-0.12394058  0.5357572 ]
 [-0.25560406 -1.3144325 ]
 [-2.0833118  -0.17978509]
 [ 1.2277584   1.1422129 ]
 [ 1.9488399  -0.29551357]
 [ 1.4923406   1.2791871 ]
 [-1.0279937  -0.38962302]
 [ 0.6210919  -0.43854827]
 [ 0.24609022 -0.2044322 ]
 [-2.0406713   0.41470617]
 [ 0.00630912 -0.95428544]
 [ 1.0348318  -0.05022401]
 [ 0.2298622  -0.14089851]
 [-1.406144    1.0771574 ]
 [ 0.52927613 -1.082466  ]
 [ 0.4701307   1.1353132 ]
 [-0.16565523  0.03931441]
 [ 0.87248427  1.8012087 ]
 [-0.00583898  1.3670379 ]
 [ 1.5350158   0.5449487 ]
 [-2.012137    0.27124256]
 [-0.20547634  1.3542424 ]
 [-0.18025523 -1.5005953 ]
 [-0.71588004 -0.2790774 ]
 [ 1.158691    0.87293553]
 [-0.83556896  1.7440767 ]
 [-0.06720523  0.14867784]
 [-0.8971017  -0.08741897]
 [-0.28453246  0.41304955]
 [-0.18931936 -1.6786495 ]
 [ 0.22720632 -0.73297673]
 [-1.5311948   0.05454918]
 [-0.27318662 -1.0315794 ]
 

In [52]:
vector = sess.run(W12 + b12)
print(vector)

[[-0.6118115  -0.68417406]
 [ 1.2628708  -1.0592258 ]
 [ 1.5656847  -0.6970696 ]
 [ 0.5023184   2.1407266 ]
 [-0.35233888  0.3658899 ]
 [-0.22267906 -0.76320493]
 [-0.25395238  0.44072536]
 [-0.4449649  -0.4409277 ]
 [-0.66669    -0.05125922]
 [ 0.1164488  -0.8661365 ]
 [-1.0893097   0.22161141]
 [-0.72485757 -1.5867488 ]
 [ 0.67136484 -0.17835538]
 [-0.24992135 -1.9288172 ]
 [ 0.01786772  0.0031626 ]
 [-0.6147143  -0.8389338 ]
 [ 0.82205915  2.2469618 ]
 [ 1.2596947   0.5987758 ]
 [ 0.36375764 -1.3999902 ]
 [-0.5104096   2.315708  ]
 [ 0.6143746  -1.4698552 ]
 [ 1.2624792   0.38900506]
 [ 1.3048835   0.14291587]
 [-1.0382769   0.17903413]
 [-1.3421984  -0.7030063 ]
 [-0.9588314  -1.7237903 ]
 [-0.01453987 -1.9618835 ]
 [-1.4414736   1.0564821 ]
 [ 0.20203158 -1.3012193 ]
 [ 0.10149613 -0.14152752]
 [ 0.1786509   0.6306413 ]
 [ 0.8967642   0.87934   ]
 [ 1.0731794   0.488325  ]
 [ 1.1189686  -0.21600804]
 [ 0.66438687 -1.0545542 ]
 [ 1.3423421   0.01233028]
 [-0.12756334  0.1980026 ]
 

In [53]:
vectors.shape

(206, 2)

In [54]:
vector.shape

(224, 2)

In [103]:
w2v_df1 = pd.DataFrame(vectors, columns = ['x1', 'x2'])
li =list(words1)
w2v_df1['word'] = li
w2v_df1 = w2v_df1[['word', 'x1', 'x2']]
# print(w2v_df)
w2v_df1
w2v_df1.to_csv('vectors1.csv');

In [56]:
w2v_df2 = pd.DataFrame(vector, columns = ['x1', 'x2'])
li =list(words2)
w2v_df2['word'] = li
w2v_df2 = w2v_df2[['word', 'x1', 'x2']]
# print(w2v_df)
w2v_df2
w2v_df2.to_csv('vectors2.csv');

In [57]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity([vectors[4]],[vectors[1]])

array([[0.9834304]], dtype=float32)

In [58]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity([vector[4]],[vector[1]])

array([[-0.99435115]], dtype=float32)

In [59]:
vectors[4]

array([-0.12394058,  0.5357572 ], dtype=float32)

In [60]:
vectors[2]

array([ 1.474749 , -2.6631548], dtype=float32)

In [61]:
vector[1]

array([ 1.2628708, -1.0592258], dtype=float32)

In [62]:
vector[2]

array([ 1.5656847, -0.6970696], dtype=float32)

In [63]:
sentence1 = "मैनानि फिसाज्लाया गसाइगाव हाथाइाव हाथाइनि डाक्टरनाव थांदों मोन मादैजों"
sentence2 =  "सोमखोरा हाथाइाव मैगं फानो लांना समाव गादलिनना गोग्लैना हाथाइआव दुखु मोनो"

In [64]:
pre_sentenced1 = "मैनानि फिसाज्ला गसाइगाव हाथाइ हाथाइनि डाक्टरनाव थांदों मादै" 
pre_sentenced2 = "सोमखोरा हाथाइ मैगं फानो लांना समाव गादलिनना गोग्लैना हाथाइआव दुखु"

In [65]:
final_sentence1 = pre_sentenced1.split()
final_sentence2 = pre_sentenced2.split()

# print('Sen1',final_sentence1)
# print('Sen2',final_sentence2)


In [88]:
w1 = list(words1)

In [84]:
w2 = list(words2)

In [90]:
for i in final_sentence1:
  if i in w1:
    print(i)
    print(w1.index(i))

मैनानि
15
फिसाज्ला
203
हाथाइ
195
डाक्टरनाव
185
मादै
48


In [91]:
for i in final_sentence1:
  if i in w2:
    print(i)
    print(w2.index(i))

फिसाज्ला
220
गसाइगाव
199
हाथाइ
211
मादै
59


In [85]:
for i in final_sentence2:
  if i in w1:
    print(i)
    print(w1.index(i))

सोमखोरा
118
हाथाइ
195
लांना
94


In [89]:
for i in final_sentence2:
  if i in w2:
    print(i)
    print(w2.index(i))

हाथाइ
211
मैगं
107
हाथाइआव
87
दुखु
201


In [92]:
indx1 = []
for i in final_sentence1:
    sum=0
    if i in w1:
        indx = w1.index(i)
        print("index",indx,i)
        for k in range(0,206):
            sum += cosine_similarity([vectors[indx]],[vectors[k]])
        indx1.append(sum/206)
        print("Sum = ",sum,"and average is",sum/206)

index 15 मैनानि
Sum =  [[-7.7514353]] and average is [[-0.03762833]]
index 203 फिसाज्ला
Sum =  [[-10.125915]] and average is [[-0.04915493]]
index 195 हाथाइ
Sum =  [[-4.331401]] and average is [[-0.02102622]]
index 185 डाक्टरनाव
Sum =  [[-1.4086733]] and average is [[-0.00683822]]
index 48 मादै
Sum =  [[3.8407202]] and average is [[0.01864427]]


In [94]:
indx2 = []
for i in final_sentence1:
    sum=0
    if i in w2:
        indx = w2.index(i)
        print("index",indx,i)
        for k in range(0,224):
            sum += cosine_similarity([vector[indx]],[vector[k]])
        indx2.append(sum/224)
        print("Sum = ",sum,"and average is",sum/224)

index 220 फिसाज्ला
Sum =  [[16.379242]] and average is [[0.07312161]]
index 199 गसाइगाव
Sum =  [[-14.801742]] and average is [[-0.06607921]]
index 211 हाथाइ
Sum =  [[4.3898582]] and average is [[0.01959758]]
index 59 मादै
Sum =  [[-2.077619]] and average is [[-0.00927509]]


In [95]:
indx3 = []
for i in final_sentence2:
    sum=0
    if i in w1:
        indx = w1.index(i)
        print("index",indx,i)
        for k in range(0,206):
            sum += cosine_similarity([vectors[indx]],[vectors[k]])
        indx2.append(sum/206)
        print("Sum = ",sum,"and average is",sum/206)

index 118 सोमखोरा
Sum =  [[-1.0742719]] and average is [[-0.00521491]]
index 195 हाथाइ
Sum =  [[-4.331401]] and average is [[-0.02102622]]
index 94 लांना
Sum =  [[0.26192874]] and average is [[0.0012715]]


In [96]:
indx4 = []
for i in final_sentence2:
    sum=0
    if i in w2:
        indx = w2.index(i)
        print("index",indx,i)
        for k in range(0,224):
            sum += cosine_similarity([vector[indx]],[vector[k]])
        indx2.append(sum/224)
        print("Sum = ",sum,"and average is",sum/224)

index 211 हाथाइ
Sum =  [[4.3898582]] and average is [[0.01959758]]
index 107 मैगं
Sum =  [[14.291524]] and average is [[0.06380145]]
index 87 हाथाइआव
Sum =  [[-8.5086355]] and average is [[-0.03798498]]
index 201 दुखु
Sum =  [[15.880394]] and average is [[0.07089461]]
